OpenThreads: OpenThreads::Mutex Class Reference
OpenThreads::Mutex Class Reference
This class provides an object-oriented thread mutex interface.
Public Types
enum MutexType { MUTEX_NORMAL, MUTEX_RECURSIVE }
Public Member Functions
Mutex (MutexType type=MUTEX_NORMAL)
Constructor.
virtual ~Mutex ()
Destructor.
MutexType getMutexType () const
virtual int lock ()
Lock the mutex.
virtual int unlock ()
Unlock the mutex.
virtual int trylock ()
Test if mutex can be locked.
Friends
class Condition
Detailed Description
This class provides an object-oriented thread mutex interface.
Member Enumeration Documentation
enum OpenThreads::Mutex::MutexType
Enumerator:
MUTEX_NORMAL
MUTEX_RECURSIVE
Constructor & Destructor Documentation
OpenThreads::Mutex::Mutex (MutexType type = MUTEX_NORMAL)
Constructor.
virtual OpenThreads::Mutex::~Mutex () [virtual]
Destructor.
Member Function Documentation
MutexType OpenThreads::Mutex::getMutexType () const [inline]
virtual int OpenThreads::Mutex::lock () [virtual]
Lock the mutex.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
Referenced by OpenThreads::ReadWriteMutex::readLock(), and OpenThreads::ReadWriteMutex::writeLock().
virtual int OpenThreads::Mutex::trylock () [virtual]
Test if mutex can be locked.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
virtual int OpenThreads::Mutex::unlock () [virtual]
Unlock the mutex.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
Referenced by OpenThreads::ReadWriteMutex::readUnlock(), and OpenThreads::ReadWriteMutex::writeUnlock().
Friends And Related Function Documentation
friend class Condition [friend]
The documentation for this class was generated from the following file:
OpenThreads/Mutex
Generated at Mon Aug 1 2011 15:39:16 for the OpenThreads by doxygen 1.7.1.