OpenSceneGraph: osgParticle::AngularDampingOperator Class Reference
osgParticle::AngularDampingOperator Class Reference
A angular damping operator applies damping constant to particle's angular velocity.
Public Member Functions
AngularDampingOperator ()
AngularDampingOperator (const AngularDampingOperator &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgParticle, AngularDampingOperator)
void setDamping (float x, float y, float z)
Set the damping factors.
void setDamping (const osg::Vec3 &damping)
void setDamping (float x)
Set the damping factors to one value.
void getDamping (float &x, float &y, float &z) const
Get the damping factors.
const osg::Vec3 & getDamping () const
void setCutoff (float low, float high)
Set the velocity cutoff factors.
void setCutoffLow (float low)
void setCutoffHigh (float low)
void getCutoff (float &low, float &high) const
Get the velocity cutoff factors.
float getCutoffLow () const
float getCutoffHigh () const
void operate (Particle *P, double dt)
Apply the acceleration to a particle. Do not call this method manually.
Protected Member Functions
virtual ~AngularDampingOperator ()
AngularDampingOperator & operator= (const AngularDampingOperator &)
Protected Attributes
osg::Vec3 _damping
float _cutoffLow
float _cutoffHigh
Detailed Description
A angular damping operator applies damping constant to particle's angular velocity.
Refer to David McAllister's Particle System API (http://www.particlesystems.org)
Constructor & Destructor Documentation
osgParticle::AngularDampingOperator::AngularDampingOperator () [inline]
osgParticle::AngularDampingOperator::AngularDampingOperator (const AngularDampingOperator & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::AngularDampingOperator::~AngularDampingOperator () [inline, protected, virtual]
Member Function Documentation
void osgParticle::AngularDampingOperator::getCutoff (float & low, float & high) const [inline]
Get the velocity cutoff factors.
References _cutoffHigh, and _cutoffLow.
float osgParticle::AngularDampingOperator::getCutoffHigh () const [inline]
References _cutoffHigh.
float osgParticle::AngularDampingOperator::getCutoffLow () const [inline]
References _cutoffLow.
void osgParticle::AngularDampingOperator::getDamping (float & x, float & y, float & z) const [inline]
Get the damping factors.
References _damping, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
const osg::Vec3& osgParticle::AngularDampingOperator::getDamping () const [inline]
References _damping.
osgParticle::AngularDampingOperator::META_Object (osgParticle , AngularDampingOperator)
void osgParticle::AngularDampingOperator::operate (Particle * P, double dt) [inline, virtual]
Apply the acceleration to a particle. Do not call this method manually.
Implements osgParticle::Operator.
References _cutoffHigh, _cutoffLow, _damping, osgParticle::Particle::getAngularVelocity(), osg::Vec3f::length2(), osgParticle::Particle::setAngularVelocity(), osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
AngularDampingOperator& osgParticle::AngularDampingOperator::operator= (const AngularDampingOperator &) [inline, protected]
void osgParticle::AngularDampingOperator::setCutoff (float low, float high) [inline]
Set the velocity cutoff factors.
References _cutoffHigh, and _cutoffLow.
void osgParticle::AngularDampingOperator::setCutoffHigh (float low) [inline]
References _cutoffHigh.
void osgParticle::AngularDampingOperator::setCutoffLow (float low) [inline]
References _cutoffLow.
void osgParticle::AngularDampingOperator::setDamping (float x) [inline]
Set the damping factors to one value.
References _damping, and osg::Vec3f::set().
void osgParticle::AngularDampingOperator::setDamping (float x, float y, float z) [inline]
Set the damping factors.
References _damping, and osg::Vec3f::set().
void osgParticle::AngularDampingOperator::setDamping (const osg::Vec3 & damping) [inline]
References _damping.
Member Data Documentation
float osgParticle::AngularDampingOperator::_cutoffHigh [protected]
Referenced by getCutoff(), getCutoffHigh(), operate(), setCutoff(), and setCutoffHigh().
float osgParticle::AngularDampingOperator::_cutoffLow [protected]
Referenced by getCutoff(), getCutoffLow(), operate(), setCutoff(), and setCutoffLow().
osg::Vec3 osgParticle::AngularDampingOperator::_damping [protected]
Referenced by getDamping(), operate(), and setDamping().
The documentation for this class was generated from the following file:
osgParticle/AngularDampingOperator
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.