OpenSceneGraph: osgManipulator::CommandManager Class Reference
osgManipulator::CommandManager Class Reference
Deprecated.
Public Types
typedef std::list
< osg::ref_ptr< Selection > > Selections
Public Member Functions
CommandManager ()
bool connect (Dragger &dragger, Selection &selection)
bool connect (Dragger &dragger, Constraint &constraint)
bool disconnect (Dragger &dragger)
Selections getConnectedSelections (Dragger &dragger)
Protected Member Functions
virtual ~CommandManager ()
Detailed Description
Deprecated.
CommandManager class is now no longer required as Dragger now matains all references to Constraints and Selections (now just generic MatrixTransforms). To replace CommandManager usage simple replace cmdMgr->connect(*dragger, *selection) with dragger->addTransformUpdating(selection) and cmdMgr->connect(*dragger, *selection) with dragger->addConstaint(constraint).
Member Typedef Documentation
typedef std::list< osg::ref_ptr<Selection> > osgManipulator::CommandManager::Selections
Constructor & Destructor Documentation
osgManipulator::CommandManager::CommandManager () [inline]
virtual osgManipulator::CommandManager::~CommandManager () [inline, protected, virtual]
Member Function Documentation
bool osgManipulator::CommandManager::connect (Dragger & dragger, Selection & selection) [inline]
References osgManipulator::Dragger::addTransformUpdating().
bool osgManipulator::CommandManager::connect (Dragger & dragger, Constraint & constraint) [inline]
References osgManipulator::Dragger::addConstraint().
bool osgManipulator::CommandManager::disconnect (Dragger & dragger) [inline]
References osgManipulator::Dragger::getConstraints(), and osgManipulator::Dragger::getDraggerCallbacks().
Selections osgManipulator::CommandManager::getConnectedSelections (Dragger & dragger) [inline]
References osgManipulator::Dragger::getDraggerCallbacks(), and osgManipulator::DraggerTransformCallback::getTransform().
The documentation for this class was generated from the following file:
osgManipulator/CommandManager
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.