OpenSceneGraph: osgParticle::CompositePlacer Class Reference
osgParticle::CompositePlacer Class Reference
A composite particle placer which allows particles to be generated from a union of placers.
Public Member Functions
CompositePlacer ()
CompositePlacer (const CompositePlacer &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgParticle, CompositePlacer)
void setPlacer (unsigned int i, Placer *p)
void addPlacer (Placer *p)
Add a child placer.
void removePlacer (unsigned int i)
Remove a child placer.
Placer * getPlacer (unsigned int i)
Get a child placer.
const Placer * getPlacer (unsigned int i) const
unsigned int getNumPlacers () const
Get number of placers.
void place (Particle *P) const
Place a particle. Do not call it manually.
float volume () const
return the volume of the box
osg::Vec3 getControlPosition () const
return the control position
Protected Types
typedef std::vector
< osg::ref_ptr< Placer > > PlacerList
Protected Member Functions
virtual ~CompositePlacer ()
CompositePlacer & operator= (const CompositePlacer &)
Protected Attributes
PlacerList _placers
Detailed Description
A composite particle placer which allows particles to be generated from a union of placers.
Member Typedef Documentation
typedef std::vector< osg::ref_ptr<Placer> > osgParticle::CompositePlacer::PlacerList [protected]
Constructor & Destructor Documentation
osgParticle::CompositePlacer::CompositePlacer () [inline]
osgParticle::CompositePlacer::CompositePlacer (const CompositePlacer & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::CompositePlacer::~CompositePlacer () [inline, protected, virtual]
Member Function Documentation
void osgParticle::CompositePlacer::addPlacer (Placer * p) [inline]
Add a child placer.
References _placers.
Referenced by setPlacer().
osg::Vec3 osgParticle::CompositePlacer::getControlPosition () const [inline, virtual]
return the control position
Implements osgParticle::Placer.
References _placers.
unsigned int osgParticle::CompositePlacer::getNumPlacers () const [inline]
Get number of placers.
References _placers.
Placer* osgParticle::CompositePlacer::getPlacer (unsigned int i) [inline]
Get a child placer.
References _placers.
const Placer* osgParticle::CompositePlacer::getPlacer (unsigned int i) const [inline]
References _placers.
osgParticle::CompositePlacer::META_Object (osgParticle , CompositePlacer)
CompositePlacer& osgParticle::CompositePlacer::operator= (const CompositePlacer &) [inline, protected]
void osgParticle::CompositePlacer::place (Particle * P) const [inline, virtual]
Place a particle. Do not call it manually.
Implements osgParticle::Placer.
References _placers, osgParticle::range< ValueType >::get_random(), and volume().
void osgParticle::CompositePlacer::removePlacer (unsigned int i) [inline]
Remove a child placer.
References _placers.
void osgParticle::CompositePlacer::setPlacer (unsigned int i, Placer * p) [inline]
References _placers, and addPlacer().
float osgParticle::CompositePlacer::volume () const [inline, virtual]
return the volume of the box
Reimplemented from osgParticle::Placer.
References _placers.
Referenced by place().
Member Data Documentation
PlacerList osgParticle::CompositePlacer::_placers [protected]
Referenced by addPlacer(), getControlPosition(), getNumPlacers(), getPlacer(), place(), removePlacer(), setPlacer(), and volume().
The documentation for this class was generated from the following file:
osgParticle/CompositePlacer
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.