OpenSceneGraph: osgParticle::DampingOperator Class Reference
osgParticle::DampingOperator Class Reference
A damping operator applies damping constant to particle's velocity.
Public Member Functions
DampingOperator ()
DampingOperator (const DampingOperator &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgParticle, DampingOperator)
void setDamping (float x, float y, float z)
Set the damping factors.
void setDamping (const osg::Vec3 &damping)
void setDamping (float x)
Set the damping factors to one value.
void getDamping (float &x, float &y, float &z) const
Get the damping factors.
const osg::Vec3 & getDamping () const
void setCutoff (float low, float high)
Set the velocity cutoff factors.
void setCutoffLow (float low)
void setCutoffHigh (float low)
void getCutoff (float &low, float &high) const
Get the velocity cutoff factors.
float getCutoffLow () const
float getCutoffHigh () const
void operate (Particle *P, double dt)
Apply the acceleration to a particle. Do not call this method manually.
Protected Member Functions
virtual ~DampingOperator ()
DampingOperator & operator= (const DampingOperator &)
Protected Attributes
osg::Vec3 _damping
float _cutoffLow
float _cutoffHigh
Detailed Description
A damping operator applies damping constant to particle's velocity.
Refer to David McAllister's Particle System API (http://www.particlesystems.org)
Constructor & Destructor Documentation
osgParticle::DampingOperator::DampingOperator () [inline]
References _damping, and osg::Vec3f::set().
osgParticle::DampingOperator::DampingOperator (const DampingOperator & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::DampingOperator::~DampingOperator () [inline, protected, virtual]
Member Function Documentation
void osgParticle::DampingOperator::getCutoff (float & low, float & high) const [inline]
Get the velocity cutoff factors.
References _cutoffHigh, and _cutoffLow.
float osgParticle::DampingOperator::getCutoffHigh () const [inline]
References _cutoffHigh.
float osgParticle::DampingOperator::getCutoffLow () const [inline]
References _cutoffLow.
void osgParticle::DampingOperator::getDamping (float & x, float & y, float & z) const [inline]
Get the damping factors.
References _damping, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
const osg::Vec3& osgParticle::DampingOperator::getDamping () const [inline]
References _damping.
osgParticle::DampingOperator::META_Object (osgParticle , DampingOperator)
void osgParticle::DampingOperator::operate (Particle * P, double dt) [inline, virtual]
Apply the acceleration to a particle. Do not call this method manually.
Implements osgParticle::Operator.
References _cutoffHigh, _cutoffLow, _damping, osgParticle::Particle::getVelocity(), osg::Vec3f::length2(), osgParticle::Particle::setVelocity(), osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
DampingOperator& osgParticle::DampingOperator::operator= (const DampingOperator &) [inline, protected]
void osgParticle::DampingOperator::setCutoff (float low, float high) [inline]
Set the velocity cutoff factors.
References _cutoffHigh, and _cutoffLow.
void osgParticle::DampingOperator::setCutoffHigh (float low) [inline]
References _cutoffHigh.
void osgParticle::DampingOperator::setCutoffLow (float low) [inline]
References _cutoffLow.
void osgParticle::DampingOperator::setDamping (float x) [inline]
Set the damping factors to one value.
References _damping, and osg::Vec3f::set().
void osgParticle::DampingOperator::setDamping (float x, float y, float z) [inline]
Set the damping factors.
References _damping, and osg::Vec3f::set().
void osgParticle::DampingOperator::setDamping (const osg::Vec3 & damping) [inline]
References _damping.
Member Data Documentation
float osgParticle::DampingOperator::_cutoffHigh [protected]
Referenced by getCutoff(), getCutoffHigh(), operate(), setCutoff(), and setCutoffHigh().
float osgParticle::DampingOperator::_cutoffLow [protected]
Referenced by getCutoff(), getCutoffLow(), operate(), setCutoff(), and setCutoffLow().
osg::Vec3 osgParticle::DampingOperator::_damping [protected]
Referenced by DampingOperator(), getDamping(), operate(), and setDamping().
The documentation for this class was generated from the following file:
osgParticle/DampingOperator
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.