OpenSceneGraph: osgUtil::IncrementalCompileOperation::CompileList Class Reference
osgUtil::IncrementalCompileOperation::CompileList Class Reference
Public Types
typedef std::list
< osg::ref_ptr< CompileOp > > CompileOps
Public Member Functions
CompileList ()
~CompileList ()
bool empty () const
void add (CompileOp *compileOp)
void add (osg::Drawable *drawable)
void add (osg::Texture *texture)
void add (osg::Program *program)
double estimatedTimeForCompile (CompileInfo &compileInfo) const
bool compile (CompileInfo &compileInfo)
Public Attributes
CompileOps _compileOps
Member Typedef Documentation
typedef std::list< osg::ref_ptr<CompileOp> > osgUtil::IncrementalCompileOperation::CompileList::CompileOps
Constructor & Destructor Documentation
osgUtil::IncrementalCompileOperation::CompileList::CompileList ()
osgUtil::IncrementalCompileOperation::CompileList::~CompileList ()
Member Function Documentation
void osgUtil::IncrementalCompileOperation::CompileList::add (CompileOp * compileOp)
void osgUtil::IncrementalCompileOperation::CompileList::add (osg::Texture * texture) [inline]
References add().
Referenced by add().
void osgUtil::IncrementalCompileOperation::CompileList::add (osg::Program * program) [inline]
References add().
Referenced by add().
void osgUtil::IncrementalCompileOperation::CompileList::add (osg::Drawable * drawable) [inline]
References add().
Referenced by add().
bool osgUtil::IncrementalCompileOperation::CompileList::compile (CompileInfo & compileInfo)
bool osgUtil::IncrementalCompileOperation::CompileList::empty () const [inline]
double osgUtil::IncrementalCompileOperation::CompileList::estimatedTimeForCompile (CompileInfo & compileInfo) const
Member Data Documentation
CompileOps osgUtil::IncrementalCompileOperation::CompileList::_compileOps
The documentation for this class was generated from the following file:
osgUtil/IncrementalCompileOperation
Generated at Mon Aug 1 2011 15:38:49 for the OpenSceneGraph by doxygen 1.7.1.