OpenSceneGraph: osgDB::EnumSerializer< C, P, B > Class Template Reference
osgDB::EnumSerializer< C, P, B > Class Template Reference
Public Types
typedef TemplateSerializer< P > ParentType
typedef P(C::* Getter)() const
typedef B(C::* Setter)(P)
Public Member Functions
EnumSerializer (const char *name, P def, Getter gf, Setter sf)
void add (const char *str, P value)
P getValue (const char *str)
const std::string & getString (P value)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (osgDB::OutputStream &os, const osg::Object &obj)
Public Attributes
Getter _getter
Setter _setter
Protected Attributes
IntLookup _lookup
template<typename C, typename P, typename B>
class osgDB::EnumSerializer< C, P, B >
Member Typedef Documentation
template<typename C , typename P , typename B > typedef P(C::* osgDB::EnumSerializer< C, P, B >::Getter)() const
template<typename C , typename P , typename B > typedef TemplateSerializer<P> osgDB::EnumSerializer< C, P, B >::ParentType
template<typename C , typename P , typename B > typedef B(C::* osgDB::EnumSerializer< C, P, B >::Setter)(P)
Constructor & Destructor Documentation
template<typename C , typename P , typename B > osgDB::EnumSerializer< C, P, B >::EnumSerializer (const char * name, P def, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C , typename P , typename B > void osgDB::EnumSerializer< C, P, B >::add (const char * str, P value) [inline]
References osgDB::EnumSerializer< C, P, B >::_lookup, and osgDB::IntLookup::add().
template<typename C , typename P , typename B > const std::string& osgDB::EnumSerializer< C, P, B >::getString (P value) [inline]
References osgDB::EnumSerializer< C, P, B >::_lookup, and osgDB::IntLookup::getString().
Referenced by osgDB::EnumSerializer< C, P, B >::write().
template<typename C , typename P , typename B > P osgDB::EnumSerializer< C, P, B >::getValue (const char * str) [inline]
References osgDB::EnumSerializer< C, P, B >::_lookup, and osgDB::IntLookup::getValue().
Referenced by osgDB::EnumSerializer< C, P, B >::read().
template<typename C , typename P , typename B > virtual bool osgDB::EnumSerializer< C, P, B >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P >.
References osgDB::TemplateSerializer< P >::_defaultValue, osgDB::TemplateSerializer< P >::_name, osgDB::EnumSerializer< C, P, B >::_setter, osgDB::EnumSerializer< C, P, B >::getValue(), osgDB::InputStream::isBinary(), and osgDB::InputStream::matchString().
template<typename C , typename P , typename B > virtual bool osgDB::EnumSerializer< C, P, B >::write (osgDB::OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P >.
References osgDB::TemplateSerializer< P >::_defaultValue, osgDB::EnumSerializer< C, P, B >::_getter, osgDB::TemplateSerializer< P >::_name, osgDB::EnumSerializer< C, P, B >::getString(), osgDB::OutputStream::isBinary(), and PROPERTY.
Member Data Documentation
template<typename C , typename P , typename B > Getter osgDB::EnumSerializer< C, P, B >::_getter
Referenced by osgDB::EnumSerializer< C, P, B >::write().
template<typename C , typename P , typename B > IntLookup osgDB::EnumSerializer< C, P, B >::_lookup [protected]
Referenced by osgDB::EnumSerializer< C, P, B >::add(), osgDB::EnumSerializer< C, P, B >::getString(), and osgDB::EnumSerializer< C, P, B >::getValue().
template<typename C , typename P , typename B > Setter osgDB::EnumSerializer< C, P, B >::_setter
Referenced by osgDB::EnumSerializer< C, P, B >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.