OpenSceneGraph: osgManipulator::Dragger Class Reference
osgManipulator::Dragger Class Reference
Base class for draggers.
Public Types
typedef std::vector
< osg::ref_ptr< Constraint > > Constraints
typedef std::vector
< osg::ref_ptr
< DraggerCallback > > DraggerCallbacks
Public Member Functions
META_Node (osgManipulator, Dragger) virtual void setParentDragger(Dragger *parent)
Set/Get parent dragger.
Dragger * getParentDragger ()
const Dragger * getParentDragger () const
virtual const CompositeDragger * getComposite () const
Returns 0 if this Dragger is not a CompositeDragger.
virtual CompositeDragger * getComposite ()
Returns 0 if this Dragger is not a CompositeDragger.
void setHandleEvents (bool flag)
bool getHandleEvents () const
void setActivationModKeyMask (unsigned int mask)
unsigned int getActivationModKeyMask () const
void setActivationKeyEvent (int key)
int getActivationKeyEvent () const
virtual void traverse (osg::NodeVisitor &nv)
Traverse downwards : calls children's accept method with NodeVisitor.
virtual bool handle (const osgGA::GUIEventAdapter &ea, osgGA::GUIActionAdapter &aa)
virtual bool handle (const PointerInfo &, const osgGA::GUIEventAdapter &, osgGA::GUIActionAdapter &)
void addConstraint (Constraint *constraint)
void removeConstraint (Constraint *constraint)
Constraints & getConstraints ()
const Constraints & getConstraints () const
void addDraggerCallback (DraggerCallback *dc)
void removeDraggerCallback (DraggerCallback *dc)
DraggerCallbacks & getDraggerCallbacks ()
const DraggerCallbacks & getDraggerCallbacks () const
void addTransformUpdating (MatrixTransform *transform)
void removeTransformUpdating (MatrixTransform *transform)
virtual void setupDefaultGeometry ()
Setup default geometry for dragger.
virtual bool receive (const MotionCommand &command)
void dispatch (MotionCommand &command)
void setDraggerActive (bool active)
bool getDraggerActive () const
Protected Member Functions
Dragger ()
Dragger (const Dragger &rhs, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
virtual ~Dragger ()
Protected Attributes
bool _handleEvents
bool _draggerActive
unsigned int _activationModKeyMask
int _activationKeyEvent
bool _activationPermittedByModKeyMask
bool _activationPermittedByKeyEvent
osgManipulator::PointerInfo _pointer
Dragger * _parentDragger
osg::ref_ptr< DraggerCallback > _selfUpdater
Constraints _constraints
DraggerCallbacks _draggerCallbacks
Detailed Description
Base class for draggers.
Concrete draggers implement the pick event handler and generate motion commands (translate, rotate, ...) and sends these command to all the DraggerCallbacks & Transforms that are connected to the Dragger that generates the commands.
Member Typedef Documentation
typedef std::vector< osg::ref_ptr<Constraint> > osgManipulator::Dragger::Constraints
typedef std::vector< osg::ref_ptr<DraggerCallback> > osgManipulator::Dragger::DraggerCallbacks
Constructor & Destructor Documentation
osgManipulator::Dragger::Dragger () [protected]
osgManipulator::Dragger::Dragger (const Dragger & rhs, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [protected]
virtual osgManipulator::Dragger::~Dragger () [protected, virtual]
Member Function Documentation
void osgManipulator::Dragger::addConstraint (Constraint * constraint)
Referenced by osgManipulator::CommandManager::connect().
void osgManipulator::Dragger::addDraggerCallback (DraggerCallback * dc)
void osgManipulator::Dragger::addTransformUpdating (MatrixTransform * transform)
Referenced by osgManipulator::CommandManager::connect().
void osgManipulator::Dragger::dispatch (MotionCommand & command)
int osgManipulator::Dragger::getActivationKeyEvent () const [inline]
unsigned int osgManipulator::Dragger::getActivationModKeyMask () const [inline]
virtual CompositeDragger* osgManipulator::Dragger::getComposite () [inline, virtual]
Returns 0 if this Dragger is not a CompositeDragger.
Reimplemented in osgManipulator::CompositeDragger.
virtual const CompositeDragger* osgManipulator::Dragger::getComposite () const [inline, virtual]
Returns 0 if this Dragger is not a CompositeDragger.
Reimplemented in osgManipulator::CompositeDragger.
Constraints& osgManipulator::Dragger::getConstraints () [inline]
Referenced by osgManipulator::CommandManager::disconnect().
const Constraints& osgManipulator::Dragger::getConstraints () const [inline]
bool osgManipulator::Dragger::getDraggerActive () const [inline]
DraggerCallbacks& osgManipulator::Dragger::getDraggerCallbacks () [inline]
Referenced by osgManipulator::CommandManager::disconnect(), and osgManipulator::CommandManager::getConnectedSelections().
const DraggerCallbacks& osgManipulator::Dragger::getDraggerCallbacks () const [inline]
bool osgManipulator::Dragger::getHandleEvents () const [inline]
Dragger* osgManipulator::Dragger::getParentDragger () [inline]
const Dragger* osgManipulator::Dragger::getParentDragger () const [inline]
virtual bool osgManipulator::Dragger::handle (const PointerInfo & , const osgGA::GUIEventAdapter & , osgGA::GUIActionAdapter &) [inline, virtual]
Reimplemented in osgManipulator::CompositeDragger.
virtual bool osgManipulator::Dragger::handle (const osgGA::GUIEventAdapter & ea, osgGA::GUIActionAdapter & aa) [virtual]
osgManipulator::Dragger::META_Node (osgManipulator , Dragger) [inline]
Set/Get parent dragger.
For simple draggers parent points to itself. For composite draggers parent points to the parent dragger that uses this dragger.
virtual bool osgManipulator::Dragger::receive (const MotionCommand & command) [virtual]
void osgManipulator::Dragger::removeConstraint (Constraint * constraint)
void osgManipulator::Dragger::removeDraggerCallback (DraggerCallback * dc)
void osgManipulator::Dragger::removeTransformUpdating (MatrixTransform * transform)
void osgManipulator::Dragger::setActivationKeyEvent (int key) [inline]
void osgManipulator::Dragger::setActivationModKeyMask (unsigned int mask) [inline]
void osgManipulator::Dragger::setDraggerActive (bool active) [inline]
void osgManipulator::Dragger::setHandleEvents (bool flag)
virtual void osgManipulator::Dragger::setupDefaultGeometry () [inline, virtual]
Setup default geometry for dragger.
Reimplemented in osgManipulator::RotateCylinderDragger, osgManipulator::RotateSphereDragger, osgManipulator::Scale1DDragger, osgManipulator::Scale2DDragger, osgManipulator::Translate1DDragger, osgManipulator::Translate2DDragger, and osgManipulator::TranslatePlaneDragger.
virtual void osgManipulator::Dragger::traverse (osg::NodeVisitor &) [virtual]
Traverse downwards : calls children's accept method with NodeVisitor.
Reimplemented from osg::Group.
Member Data Documentation
int osgManipulator::Dragger::_activationKeyEvent [protected]
unsigned int osgManipulator::Dragger::_activationModKeyMask [protected]
bool osgManipulator::Dragger::_activationPermittedByKeyEvent [protected]
bool osgManipulator::Dragger::_activationPermittedByModKeyMask [protected]
Constraints osgManipulator::Dragger::_constraints [protected]
bool osgManipulator::Dragger::_draggerActive [protected]
DraggerCallbacks osgManipulator::Dragger::_draggerCallbacks [protected]
bool osgManipulator::Dragger::_handleEvents [protected]
Dragger* osgManipulator::Dragger::_parentDragger [protected]
osgManipulator::PointerInfo osgManipulator::Dragger::_pointer [protected]
osg::ref_ptr<DraggerCallback> osgManipulator::Dragger::_selfUpdater [protected]
The documentation for this class was generated from the following file:
osgManipulator/Dragger
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.