OpenSceneGraph: osg::ElapsedTime Class Reference
osg::ElapsedTime Class Reference
Helper class for timing sections of code.
Public Member Functions
ElapsedTime (double *elapsedTime, osg::Timer *timer=0)
ElapsedTime (osg::Timer *timer=0)
~ElapsedTime ()
void reset ()
double elapsedTime () const
elapsed time in seconds.
double elapsedTime_m () const
elapsed time in milliseconds.
double elapsedTime_u () const
elapsed time in microseconds.
double elapsedTime_n () const
elapsed time in nanoseconds.
void finish ()
Protected Member Functions
void init (osg::Timer *timer)
Protected Attributes
double * _time
Timer * _timer
Timer_t _startTick
Detailed Description
Helper class for timing sections of code.
Constructor & Destructor Documentation
osg::ElapsedTime::ElapsedTime (double * elapsedTime, osg::Timer * timer = 0) [inline]
References init().
osg::ElapsedTime::ElapsedTime (osg::Timer * timer = 0) [inline]
References init().
osg::ElapsedTime::~ElapsedTime () [inline]
References finish().
Member Function Documentation
double osg::ElapsedTime::elapsedTime () const [inline]
elapsed time in seconds.
References _startTick, _timer, osg::Timer::delta_s(), and osg::Timer::tick().
double osg::ElapsedTime::elapsedTime_m () const [inline]
elapsed time in milliseconds.
References _startTick, _timer, osg::Timer::delta_m(), and osg::Timer::tick().
double osg::ElapsedTime::elapsedTime_n () const [inline]
elapsed time in nanoseconds.
References _startTick, _timer, osg::Timer::delta_n(), and osg::Timer::tick().
double osg::ElapsedTime::elapsedTime_u () const [inline]
elapsed time in microseconds.
References _startTick, _timer, osg::Timer::delta_u(), and osg::Timer::tick().
void osg::ElapsedTime::finish () [inline]
References _startTick, _time, _timer, osg::Timer::delta_s(), and osg::Timer::tick().
Referenced by ~ElapsedTime().
void osg::ElapsedTime::init (osg::Timer * timer) [inline, protected]
References _startTick, _timer, osg::Timer::instance(), and osg::Timer::tick().
Referenced by ElapsedTime().
void osg::ElapsedTime::reset () [inline]
References _startTick, _timer, and osg::Timer::tick().
Member Data Documentation
Timer_t osg::ElapsedTime::_startTick [protected]
Referenced by elapsedTime(), elapsedTime_m(), elapsedTime_n(), elapsedTime_u(), finish(), init(), and reset().
double* osg::ElapsedTime::_time [protected]
Referenced by finish().
Timer* osg::ElapsedTime::_timer [protected]
Referenced by elapsedTime(), elapsedTime_m(), elapsedTime_n(), elapsedTime_u(), finish(), init(), and reset().
The documentation for this class was generated from the following file:
osg/Timer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.