OpenSceneGraph: osgManipulator::DraggerCallback Class Reference
osgManipulator::DraggerCallback Class Reference
Public Member Functions
DraggerCallback ()
DraggerCallback (const DraggerCallback &, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgManipulator, DraggerCallback)
virtual bool receive (const MotionCommand &)
Receive motion commands.
virtual bool receive (const TranslateInLineCommand &command)
virtual bool receive (const TranslateInPlaneCommand &command)
virtual bool receive (const Scale1DCommand &command)
virtual bool receive (const Scale2DCommand &command)
virtual bool receive (const ScaleUniformCommand &command)
virtual bool receive (const Rotate3DCommand &command)
Constructor & Destructor Documentation
osgManipulator::DraggerCallback::DraggerCallback () [inline]
osgManipulator::DraggerCallback::DraggerCallback (const DraggerCallback & , const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
Member Function Documentation
osgManipulator::DraggerCallback::META_Object (osgManipulator , DraggerCallback)
virtual bool osgManipulator::DraggerCallback::receive (const Rotate3DCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::DraggerCallback::receive (const ScaleUniformCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::DraggerCallback::receive (const Scale2DCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::DraggerCallback::receive (const Scale1DCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::DraggerCallback::receive (const TranslateInPlaneCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::DraggerCallback::receive (const TranslateInLineCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::DraggerCallback::receive (const MotionCommand &) [inline, virtual]
Receive motion commands.
Returns true on success.
Reimplemented in osgManipulator::DraggerTransformCallback.
The documentation for this class was generated from the following file:
osgManipulator/Dragger
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.