OpenSceneGraph: osgDB::GLenumSerializer< C, P > Class Template Reference
osgDB::GLenumSerializer< C, P > Class Template Reference
Public Types
typedef TemplateSerializer< P > ParentType
typedef P(C::* Getter)() const
typedef void(C::* Setter)(P)
Public Member Functions
GLenumSerializer (const char *name, P def, Getter gf, Setter sf)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
Public Attributes
Getter _getter
Setter _setter
template<typename C, typename P>
class osgDB::GLenumSerializer< C, P >
Member Typedef Documentation
template<typename C , typename P > typedef P(C::* osgDB::GLenumSerializer< C, P >::Getter)() const
template<typename C , typename P > typedef TemplateSerializer<P> osgDB::GLenumSerializer< C, P >::ParentType
template<typename C , typename P > typedef void(C::* osgDB::GLenumSerializer< C, P >::Setter)(P)
Constructor & Destructor Documentation
template<typename C , typename P > osgDB::GLenumSerializer< C, P >::GLenumSerializer (const char * name, P def, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C , typename P > virtual bool osgDB::GLenumSerializer< C, P >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P >.
References osgDB::TemplateSerializer< P >::_defaultValue, osgDB::TemplateSerializer< P >::_name, osgDB::GLenumSerializer< C, P >::_setter, DEF_GLENUM, osgDB::InputStream::isBinary(), and osgDB::InputStream::matchString().
template<typename C , typename P > virtual bool osgDB::GLenumSerializer< C, P >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P >.
References osgDB::TemplateSerializer< P >::_defaultValue, osgDB::GLenumSerializer< C, P >::_getter, osgDB::TemplateSerializer< P >::_name, GLENUM, osgDB::OutputStream::isBinary(), and PROPERTY.
Member Data Documentation
template<typename C , typename P > Getter osgDB::GLenumSerializer< C, P >::_getter
Referenced by osgDB::GLenumSerializer< C, P >::write().
template<typename C , typename P > Setter osgDB::GLenumSerializer< C, P >::_setter
Referenced by osgDB::GLenumSerializer< C, P >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.