OpenSceneGraph: osg::GLBufferObject Class Reference
osg::GLBufferObject Class Reference
Classes
struct BufferEntry
class Extensions
Extensions class which encapsulates the querying of extensions and associated function pointers, and provide convenience wrappers to check for the extensions or use the associated functions.
Public Member Functions
GLBufferObject (unsigned int contextID, BufferObject *bufferObject, unsigned int glObjectID=0)
void setProfile (const BufferObjectProfile &profile)
const BufferObjectProfile & getProfile () const
void setBufferObject (BufferObject *bufferObject)
BufferObject * getBufferObject ()
unsigned int getContextID () const
GLuint & getGLObjectID ()
GLuint getGLObjectID () const
GLsizeiptrARB getOffset (unsigned int i) const
void bindBuffer ()
void unbindBuffer ()
bool isDirty () const
void dirty ()
void clear ()
void compileBuffer ()
void deleteGLObject ()
void assign (BufferObject *bufferObject)
bool isPBOSupported () const
Static Public Member Functions
static GLBufferObject * createGLBufferObject (unsigned int contextID, const BufferObject *bufferObject)
static void deleteAllBufferObjects (unsigned int contextID)
static void discardAllBufferObjects (unsigned int contextID)
static void flushAllDeletedBufferObjects (unsigned int contextID)
static void discardAllDeletedBufferObjects (unsigned int contextID)
static void flushDeletedBufferObjects (unsigned int contextID, double currentTime, double &availbleTime)
static void releaseGLBufferObject (unsigned int contextID, GLBufferObject *to)
static Extensions * getExtensions (unsigned int contextID, bool createIfNotInitalized)
Function to call to get the extension of a specified context.
static void setExtensions (unsigned int contextID, Extensions *extensions)
setExtensions allows users to override the extensions across graphics contexts.
Public Attributes
GLBufferObjectSet * _set
GLBufferObject * _previous
GLBufferObject * _next
unsigned int _frameLastUsed
Extensions * _extensions
Protected Types
typedef std::vector< BufferEntry > BufferEntries
Protected Member Functions
virtual ~GLBufferObject ()
unsigned int computeBufferAlignment (unsigned int pos, unsigned int bufferAlignment) const
Protected Attributes
unsigned int _contextID
GLuint _glObjectID
BufferObjectProfile _profile
unsigned int _allocatedSize
bool _dirty
BufferEntries _bufferEntries
BufferObject * _bufferObject
Member Typedef Documentation
typedef std::vector<BufferEntry> osg::GLBufferObject::BufferEntries [protected]
Constructor & Destructor Documentation
osg::GLBufferObject::GLBufferObject (unsigned int contextID, BufferObject * bufferObject, unsigned int glObjectID = 0)
virtual osg::GLBufferObject::~GLBufferObject () [protected, virtual]
Member Function Documentation
void osg::GLBufferObject::assign (BufferObject * bufferObject)
void osg::GLBufferObject::bindBuffer () [inline]
References _extensions, _glObjectID, _profile, _set, osg::BufferObjectProfile::_target, osg::GLBufferObject::Extensions::glBindBuffer(), and osg::GLBufferObjectSet::moveToBack().
Referenced by osg::State::bindElementBufferObject(), osg::State::bindPixelBufferObject(), and osg::State::bindVertexBufferObject().
void osg::GLBufferObject::clear ()
void osg::GLBufferObject::compileBuffer ()
Referenced by osg::State::bindElementBufferObject(), osg::State::bindPixelBufferObject(), and osg::State::bindVertexBufferObject().
unsigned int osg::GLBufferObject::computeBufferAlignment (unsigned int pos, unsigned int bufferAlignment) const [inline, protected]
static GLBufferObject* osg::GLBufferObject::createGLBufferObject (unsigned int contextID, const BufferObject * bufferObject) [static]
Referenced by osg::BufferObject::getOrCreateGLBufferObject().
static void osg::GLBufferObject::deleteAllBufferObjects (unsigned int contextID) [static]
void osg::GLBufferObject::deleteGLObject ()
void osg::GLBufferObject::dirty () [inline]
static void osg::GLBufferObject::discardAllBufferObjects (unsigned int contextID) [static]
static void osg::GLBufferObject::discardAllDeletedBufferObjects (unsigned int contextID) [static]
static void osg::GLBufferObject::flushAllDeletedBufferObjects (unsigned int contextID) [static]
static void osg::GLBufferObject::flushDeletedBufferObjects (unsigned int contextID, double currentTime, double & availbleTime) [static]
BufferObject* osg::GLBufferObject::getBufferObject () [inline]
unsigned int osg::GLBufferObject::getContextID () const [inline]
static Extensions* osg::GLBufferObject::getExtensions (unsigned int contextID, bool createIfNotInitalized) [static]
Function to call to get the extension of a specified context.
If the Extension object for that context has not yet been created and the 'createIfNotInitalized' flag been set to false then returns NULL. If 'createIfNotInitalized' is true then the Extensions object is automatically created. However, in this case the extension object is only created with the graphics context associated with ContextID..
GLuint& osg::GLBufferObject::getGLObjectID () [inline]
GLuint osg::GLBufferObject::getGLObjectID () const [inline]
GLsizeiptrARB osg::GLBufferObject::getOffset (unsigned int i) const [inline]
Referenced by osg::State::setColorPointer(), osg::State::setFogCoordPointer(), osg::State::setNormalPointer(), osg::State::setSecondaryColorPointer(), osg::State::setTexCoordPointer(), osg::State::setVertexAttribPointer(), and osg::State::setVertexPointer().
const BufferObjectProfile& osg::GLBufferObject::getProfile () const [inline]
bool osg::GLBufferObject::isDirty () const [inline]
Referenced by osg::State::bindElementBufferObject(), osg::State::bindPixelBufferObject(), and osg::State::bindVertexBufferObject().
bool osg::GLBufferObject::isPBOSupported () const [inline]
static void osg::GLBufferObject::releaseGLBufferObject (unsigned int contextID, GLBufferObject * to) [static]
void osg::GLBufferObject::setBufferObject (BufferObject * bufferObject)
static void osg::GLBufferObject::setExtensions (unsigned int contextID, Extensions * extensions) [static]
setExtensions allows users to override the extensions across graphics contexts.
typically used when you have different extensions supported across graphics pipes but need to ensure that they all use the same low common denominator extensions.
void osg::GLBufferObject::setProfile (const BufferObjectProfile & profile) [inline]
void osg::GLBufferObject::unbindBuffer () [inline]
Member Data Documentation
unsigned int osg::GLBufferObject::_allocatedSize [protected]
BufferEntries osg::GLBufferObject::_bufferEntries [protected]
BufferObject* osg::GLBufferObject::_bufferObject [protected]
unsigned int osg::GLBufferObject::_contextID [protected]
bool osg::GLBufferObject::_dirty [protected]
Extensions* osg::GLBufferObject::_extensions
Referenced by bindBuffer().
unsigned int osg::GLBufferObject::_frameLastUsed
GLuint osg::GLBufferObject::_glObjectID [protected]
Referenced by bindBuffer().
GLBufferObject* osg::GLBufferObject::_next
GLBufferObject* osg::GLBufferObject::_previous
BufferObjectProfile osg::GLBufferObject::_profile [protected]
Referenced by bindBuffer().
GLBufferObjectSet* osg::GLBufferObject::_set
Referenced by bindBuffer().
The documentation for this class was generated from the following file:
osg/BufferObject
Generated at Mon Aug 1 2011 15:38:45 for the OpenSceneGraph by doxygen 1.7.1.