OpenSceneGraph: osgDB::ListSerializer< C, P > Class Template Reference
osgDB::ListSerializer< C, P > Class Template Reference
Public Types
typedef P::value_type ValueType
typedef P::const_iterator ConstIterator
typedef const P &(C::* Getter)() const
typedef void(C::* Setter)(const P &)
Public Member Functions
ListSerializer (const char *name, Getter gf, Setter sf)
virtual const std::string & getName () const
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
Public Attributes
std::string _name
Getter _getter
Setter _setter
template<typename C, typename P>
class osgDB::ListSerializer< C, P >
Member Typedef Documentation
template<typename C , typename P > typedef P::const_iterator osgDB::ListSerializer< C, P >::ConstIterator
template<typename C , typename P > typedef const P&(C::* osgDB::ListSerializer< C, P >::Getter)() const
template<typename C , typename P > typedef void(C::* osgDB::ListSerializer< C, P >::Setter)(const P &)
template<typename C , typename P > typedef P::value_type osgDB::ListSerializer< C, P >::ValueType
Constructor & Destructor Documentation
template<typename C , typename P > osgDB::ListSerializer< C, P >::ListSerializer (const char * name, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C , typename P > virtual const std::string& osgDB::ListSerializer< C, P >::getName () const [inline, virtual]
Implements osgDB::BaseSerializer.
References osgDB::ListSerializer< C, P >::_name.
template<typename C , typename P > virtual bool osgDB::ListSerializer< C, P >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::BaseSerializer.
References osgDB::ListSerializer< C, P >::_name, osgDB::ListSerializer< C, P >::_setter, osgDB::InputStream::isBinary(), and osgDB::InputStream::matchString().
template<typename C , typename P > virtual bool osgDB::ListSerializer< C, P >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::BaseSerializer.
References osgDB::ListSerializer< C, P >::_getter, osgDB::ListSerializer< C, P >::_name, osgDB::OutputStream::isBinary(), and PROPERTY.
Member Data Documentation
template<typename C , typename P > Getter osgDB::ListSerializer< C, P >::_getter
Referenced by osgDB::ListSerializer< C, P >::write().
template<typename C , typename P > std::string osgDB::ListSerializer< C, P >::_name
Referenced by osgDB::ListSerializer< C, P >::getName(), osgDB::ListSerializer< C, P >::read(), and osgDB::ListSerializer< C, P >::write().
template<typename C , typename P > Setter osgDB::ListSerializer< C, P >::_setter
Referenced by osgDB::ListSerializer< C, P >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.