OpenSceneGraph: osgDB::IntLookup Class Reference
osgDB::IntLookup Class Reference
Public Types
typedef int Value
typedef std::map< std::string,
Value > StringToValue
typedef std::map< Value,
std::string > ValueToString
Public Member Functions
IntLookup ()
unsigned int size () const
void add (const char *str, Value value)
Value getValue (const char *str)
const std::string & getString (Value value)
Protected Attributes
StringToValue _stringToValue
ValueToString _valueToString
Member Typedef Documentation
typedef std::map<std::string, Value> osgDB::IntLookup::StringToValue
typedef int osgDB::IntLookup::Value
typedef std::map<Value, std::string> osgDB::IntLookup::ValueToString
Constructor & Destructor Documentation
osgDB::IntLookup::IntLookup () [inline]
Member Function Documentation
void osgDB::IntLookup::add (const char * str, Value value) [inline]
References _stringToValue, _valueToString, osg::notify(), and osg::WARN.
Referenced by osgDB::EnumSerializer< C, P, B >::add().
const std::string& osgDB::IntLookup::getString (Value value) [inline]
References _valueToString.
Referenced by osgDB::EnumSerializer< C, P, B >::getString().
Value osgDB::IntLookup::getValue (const char * str) [inline]
References _stringToValue.
Referenced by osgDB::EnumSerializer< C, P, B >::getValue().
unsigned int osgDB::IntLookup::size () const [inline]
References _stringToValue.
Member Data Documentation
StringToValue osgDB::IntLookup::_stringToValue [protected]
Referenced by add(), getValue(), and size().
ValueToString osgDB::IntLookup::_valueToString [protected]
Referenced by add(), and getString().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.