OpenSceneGraph: osgDB::MatrixSerializer< C > Class Template Reference
osgDB::MatrixSerializer< C > Class Template Reference
Public Types
typedef TemplateSerializer
< osg::Matrix > ParentType
typedef const osg::Matrix &(C::* Getter)() const
typedef void(C::* Setter)(const osg::Matrix &)
Public Member Functions
MatrixSerializer (const char *name, const osg::Matrix &def, Getter gf, Setter sf)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
Public Attributes
Getter _getter
Setter _setter
Protected Member Functions
void readMatrixImplementation (InputStream &is, osg::Matrix &matrix)
template<typename C>
class osgDB::MatrixSerializer< C >
Member Typedef Documentation
template<typename C > typedef const osg::Matrix&(C::* osgDB::MatrixSerializer< C >::Getter)() const
template<typename C > typedef TemplateSerializer<osg::Matrix> osgDB::MatrixSerializer< C >::ParentType
template<typename C > typedef void(C::* osgDB::MatrixSerializer< C >::Setter)(const osg::Matrix &)
Constructor & Destructor Documentation
template<typename C > osgDB::MatrixSerializer< C >::MatrixSerializer (const char * name, const osg::Matrix & def, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C > virtual bool osgDB::MatrixSerializer< C >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< osg::Matrix >.
References osgDB::TemplateSerializer< osg::Matrix >::_defaultValue, osgDB::TemplateSerializer< osg::Matrix >::_name, osgDB::MatrixSerializer< C >::_setter, osgDB::InputStream::isBinary(), osgDB::InputStream::matchString(), and osgDB::MatrixSerializer< C >::readMatrixImplementation().
template<typename C > void osgDB::MatrixSerializer< C >::readMatrixImplementation (InputStream & is, osg::Matrix & matrix) [inline, protected]
Referenced by osgDB::MatrixSerializer< C >::read().
template<typename C > virtual bool osgDB::MatrixSerializer< C >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< osg::Matrix >.
References osgDB::TemplateSerializer< osg::Matrix >::_defaultValue, osgDB::MatrixSerializer< C >::_getter, osgDB::TemplateSerializer< osg::Matrix >::_name, osgDB::OutputStream::isBinary(), and PROPERTY.
Member Data Documentation
template<typename C > Getter osgDB::MatrixSerializer< C >::_getter
Referenced by osgDB::MatrixSerializer< C >::write().
template<typename C > Setter osgDB::MatrixSerializer< C >::_setter
Referenced by osgDB::MatrixSerializer< C >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.