OpenSceneGraph: osgDB::ObjectSerializer< C, P > Class Template Reference
osgDB::ObjectSerializer< C, P > Class Template Reference
Public Types
typedef TemplateSerializer< P * > ParentType
typedef const P *(C::* Getter)() const
typedef void(C::* Setter)(P *)
Public Member Functions
ObjectSerializer (const char *name, P *def, Getter gf, Setter sf)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
Public Attributes
Getter _getter
Setter _setter
template<typename C, typename P>
class osgDB::ObjectSerializer< C, P >
Member Typedef Documentation
template<typename C , typename P > typedef const P*(C::* osgDB::ObjectSerializer< C, P >::Getter)() const
template<typename C , typename P > typedef TemplateSerializer<P*> osgDB::ObjectSerializer< C, P >::ParentType
template<typename C , typename P > typedef void(C::* osgDB::ObjectSerializer< C, P >::Setter)(P *)
Constructor & Destructor Documentation
template<typename C , typename P > osgDB::ObjectSerializer< C, P >::ObjectSerializer (const char * name, P * def, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C , typename P > virtual bool osgDB::ObjectSerializer< C, P >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P * >.
References osgDB::TemplateSerializer< P * >::_defaultValue, osgDB::TemplateSerializer< P * >::_name, osgDB::ObjectSerializer< C, P >::_setter, osgDB::InputStream::isBinary(), osgDB::InputStream::matchString(), and osgDB::InputStream::readObject().
template<typename C , typename P > virtual bool osgDB::ObjectSerializer< C, P >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P * >.
References osgDB::TemplateSerializer< P * >::_defaultValue, osgDB::ObjectSerializer< C, P >::_getter, osgDB::TemplateSerializer< P * >::_name, osgDB::OutputStream::isBinary(), PROPERTY, and osgDB::OutputStream::writeObject().
Member Data Documentation
template<typename C , typename P > Getter osgDB::ObjectSerializer< C, P >::_getter
Referenced by osgDB::ObjectSerializer< C, P >::write().
template<typename C , typename P > Setter osgDB::ObjectSerializer< C, P >::_setter
Referenced by osgDB::ObjectSerializer< C, P >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.