OpenSceneGraph: osgDB::Options Class Reference
osgDB::Options Class Reference
Options base class used for passing options into plugins to control their operation.
Public Types
enum CacheHintOptions {
CACHE_NONE = 0, CACHE_NODES = 1<<0, CACHE_IMAGES = 1<<1, CACHE_HEIGHTFIELDS = 1<<2,
CACHE_ARCHIVES = 1<<3, CACHE_OBJECTS = 1<<4, CACHE_SHADERS = 1<<5, CACHE_ALL
}
bit mask for setting up which object types get cached by readObject/Image/HeightField/Node(filename) calls
enum PrecisionHint {
FLOAT_PRECISION_ALL = 0, DOUBLE_PRECISION_VERTEX = 1<<0, DOUBLE_PRECISION_NORMAL = 1<<1, DOUBLE_PRECISION_COLOR = 1<<2,
DOUBLE_PRECISION_SECONDARY_COLOR = 1<<3, DOUBLE_PRECISION_FOG_COORD = 1<<4, DOUBLE_PRECISION_TEX_COORD = 1<<5, DOUBLE_PRECISION_VERTEX_ATTRIB = 1<<6,
DOUBLE_PRECISION_ALL
}
Bit mask for which geometry attributes should be imported with double precision where source data is held in double precision This is useful for data that will be pre-processed before rendering.
enum BuildKdTreesHint { NO_PREFERENCE, DO_NOT_BUILD_KDTREES, BUILD_KDTREES }
range of options of whether to build kdtrees automatically on loading
Public Member Functions
Options ()
Options (const std::string &str)
Options (const Options &options, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgDB, Options)
Options * cloneOptions (const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY) const
void setOptionString (const std::string &str)
Set the general Options string.
const std::string & getOptionString () const
Get the general Options string.
void setDatabasePath (const std::string &str)
Set the database path to use a hint of where to look when loading models.
FilePathList & getDatabasePathList ()
Get the database path which is used a hint of where to look when loading models.
const FilePathList & getDatabasePathList () const
Get the const database path which is used a hint of where to look when loading models.
void setObjectCacheHint (CacheHintOptions useObjectCache)
Set whether the Registry::ObjectCache should be used by default.
CacheHintOptions getObjectCacheHint () const
Get whether the Registry::ObjectCache should be used by default.
void setPrecisionHint (PrecisionHint hint)
Set which geometry attributes plugins should import at double precision.
PrecisionHint getPrecisionHint () const
Get which geometry attributes plugins should import at double precision.
void setBuildKdTreesHint (BuildKdTreesHint hint)
Set whether the KdTrees should be built for geometry in the loader model.
BuildKdTreesHint getBuildKdTreesHint () const
Get whether the KdTrees should be built for geometry in the loader model.
void setAuthenticationMap (AuthenticationMap *authenticationMap)
Set the password map to be used by plugins when access files from secure locations.
const AuthenticationMap * getAuthenticationMap () const
Get the password map to be used by plugins when access files from secure locations.
void setPluginData (const std::string &s, void *v) const
Sets a plugindata value PluginData with a string.
void * getPluginData (const std::string &s)
Get a value from the PluginData.
const void * getPluginData (const std::string &s) const
Get a value from the PluginData.
void removePluginData (const std::string &s) const
Remove a value from the PluginData.
unsigned int getNumPluginData () const
Get number of PluginData values.
void setPluginStringData (const std::string &s, const std::string &v) const
Sets a plugindata value PluginData with a string.
std::string & getPluginStringData (const std::string &s)
Get a string from the PluginStrData.
const std::string getPluginStringData (const std::string &s) const
Get a value from the PluginData.
void removePluginStringData (const std::string &s) const
Remove a value from the PluginData.
unsigned int getNumPluginStringData () const
Get number of PluginStrData values.
void parsePluginStringData (const std::string &str, char separator1=' ', char separator2='=')
Parse string into plugin string data.
void setFindFileCallback (FindFileCallback *cb)
Set the find callback to use in place of the default findFile calls.
FindFileCallback * getFindFileCallback () const
Get the const findFile callback.
void setReadFileCallback (ReadFileCallback *cb)
Set the read callback to use in place of the default readFile calls.
ReadFileCallback * getReadFileCallback () const
Get the const readFile callback.
void setWriteFileCallback (WriteFileCallback *cb)
Set the callback to use in place of the default writeFile calls.
WriteFileCallback * getWriteFileCallback () const
Get the const writeFile callback.
void setFileLocationCallback (FileLocationCallback *cb)
Set the callback to use inform the DatabasePager whether a file is located on local or remote file system.
FileLocationCallback * getFileLocationCallback () const
Get the callback to use inform the DatabasePager whether a file is located on local or remote file system.
void setFileCache (FileCache *fileCache)
Set the FileCache that is used to manage local storage of files downloaded from the internet.
FileCache * getFileCache () const
Get the FileCache that is used to manage local storage of files downloaded from the internet.
void setTerrain (osg::observer_ptr< osg::Node > &terrain)
Set the terrain observer_ptr, use to decorate any osgTerrain subgraphs.
const osg::observer_ptr
< osg::Node > & getTerrain () const
Get the terrain observer_ptr, use to decorate any osgTerrain subgraphs.
Protected Types
typedef std::map< std::string,
void * > PluginDataMap
typedef std::map< std::string,
std::string > PluginStringDataMap
Protected Member Functions
virtual ~Options ()
Protected Attributes
std::string _str
FilePathList _databasePaths
CacheHintOptions _objectCacheHint
PrecisionHint _precisionHint
BuildKdTreesHint _buildKdTreesHint
osg::ref_ptr< AuthenticationMap > _authenticationMap
PluginDataMap _pluginData
PluginStringDataMap _pluginStringData
osg::ref_ptr< FindFileCallback > _findFileCallback
osg::ref_ptr< ReadFileCallback > _readFileCallback
osg::ref_ptr< WriteFileCallback > _writeFileCallback
osg::ref_ptr
< FileLocationCallback > _fileLocationCallback
osg::ref_ptr< FileCache > _fileCache
osg::observer_ptr< osg::Node > _terrain
Detailed Description
Options base class used for passing options into plugins to control their operation.
Member Typedef Documentation
typedef std::map<std::string,void*> osgDB::Options::PluginDataMap [protected]
typedef std::map<std::string,std::string> osgDB::Options::PluginStringDataMap [protected]
Member Enumeration Documentation
enum osgDB::Options::BuildKdTreesHint
range of options of whether to build kdtrees automatically on loading
Enumerator:
NO_PREFERENCE
DO_NOT_BUILD_KDTREES
BUILD_KDTREES
enum osgDB::Options::CacheHintOptions
bit mask for setting up which object types get cached by readObject/Image/HeightField/Node(filename) calls
Enumerator:
CACHE_NONE
do not cache objects of any type
CACHE_NODES
cache nodes loaded via readNode(filename)
CACHE_IMAGES
cache images loaded via readImage(filename)
CACHE_HEIGHTFIELDS
cache heightfield loaded via readHeightField(filename)
CACHE_ARCHIVES
cache heightfield loaded via readHeightField(filename)
CACHE_OBJECTS
cache objects loaded via readObject(filename)
CACHE_SHADERS
cache shaders loaded via readShader(filename)
CACHE_ALL
cache on all read*(filename) calls
enum osgDB::Options::PrecisionHint
Bit mask for which geometry attributes should be imported with double precision where source data is held in double precision This is useful for data that will be pre-processed before rendering.
In general the geometry should be converted to floating point before rendering to ensure good performance.
Enumerator:
FLOAT_PRECISION_ALL
DOUBLE_PRECISION_VERTEX
DOUBLE_PRECISION_NORMAL
DOUBLE_PRECISION_COLOR
DOUBLE_PRECISION_SECONDARY_COLOR
DOUBLE_PRECISION_FOG_COORD
DOUBLE_PRECISION_TEX_COORD
DOUBLE_PRECISION_VERTEX_ATTRIB
DOUBLE_PRECISION_ALL
Constructor & Destructor Documentation
osgDB::Options::Options () [inline]
osgDB::Options::Options (const std::string & str) [inline]
osgDB::Options::Options (const Options & options, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY)
virtual osgDB::Options::~Options () [inline, protected, virtual]
Member Function Documentation
Options* osgDB::Options::cloneOptions (const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) const [inline]
References osg::clone().
const AuthenticationMap* osgDB::Options::getAuthenticationMap () const [inline]
Get the password map to be used by plugins when access files from secure locations.
BuildKdTreesHint osgDB::Options::getBuildKdTreesHint () const [inline]
Get whether the KdTrees should be built for geometry in the loader model.
Referenced by osgDB::Registry::_buildKdTreeIfRequired().
FilePathList& osgDB::Options::getDatabasePathList () [inline]
Get the database path which is used a hint of where to look when loading models.
const FilePathList& osgDB::Options::getDatabasePathList () const [inline]
Get the const database path which is used a hint of where to look when loading models.
FileCache* osgDB::Options::getFileCache () const [inline]
Get the FileCache that is used to manage local storage of files downloaded from the internet.
FileLocationCallback* osgDB::Options::getFileLocationCallback () const [inline]
Get the callback to use inform the DatabasePager whether a file is located on local or remote file system.
FindFileCallback* osgDB::Options::getFindFileCallback () const [inline]
Get the const findFile callback.
Referenced by osgDB::Registry::findDataFile(), and osgDB::Registry::findLibraryFile().
unsigned int osgDB::Options::getNumPluginData () const [inline]
Get number of PluginData values.
unsigned int osgDB::Options::getNumPluginStringData () const [inline]
Get number of PluginStrData values.
CacheHintOptions osgDB::Options::getObjectCacheHint () const [inline]
Get whether the Registry::ObjectCache should be used by default.
const std::string& osgDB::Options::getOptionString () const [inline]
Get the general Options string.
void* osgDB::Options::getPluginData (const std::string & s) [inline]
Get a value from the PluginData.
const void* osgDB::Options::getPluginData (const std::string & s) const [inline]
Get a value from the PluginData.
std::string& osgDB::Options::getPluginStringData (const std::string & s) [inline]
Get a string from the PluginStrData.
const std::string osgDB::Options::getPluginStringData (const std::string & s) const [inline]
Get a value from the PluginData.
PrecisionHint osgDB::Options::getPrecisionHint () const [inline]
Get which geometry attributes plugins should import at double precision.
ReadFileCallback* osgDB::Options::getReadFileCallback () const [inline]
Get the const readFile callback.
Referenced by osgDB::Registry::openArchive(), osgDB::Registry::readHeightField(), osgDB::Registry::readImage(), osgDB::Registry::readNode(), osgDB::Registry::readObject(), and osgDB::Registry::readShader().
const osg::observer_ptr<osg::Node>& osgDB::Options::getTerrain () const [inline]
Get the terrain observer_ptr, use to decorate any osgTerrain subgraphs.
WriteFileCallback* osgDB::Options::getWriteFileCallback () const [inline]
Get the const writeFile callback.
Referenced by osgDB::Registry::writeHeightField(), osgDB::Registry::writeImage(), osgDB::Registry::writeNode(), osgDB::Registry::writeObject(), and osgDB::Registry::writeShader().
osgDB::Options::META_Object (osgDB , Options)
void osgDB::Options::parsePluginStringData (const std::string & str, char separator1 = ' ', char separator2 = '=')
Parse string into plugin string data.
This will be automatically done in Options(const std::string&)
void osgDB::Options::removePluginData (const std::string & s) const [inline]
Remove a value from the PluginData.
void osgDB::Options::removePluginStringData (const std::string & s) const [inline]
Remove a value from the PluginData.
void osgDB::Options::setAuthenticationMap (AuthenticationMap * authenticationMap) [inline]
Set the password map to be used by plugins when access files from secure locations.
void osgDB::Options::setBuildKdTreesHint (BuildKdTreesHint hint) [inline]
Set whether the KdTrees should be built for geometry in the loader model.
void osgDB::Options::setDatabasePath (const std::string & str) [inline]
Set the database path to use a hint of where to look when loading models.
void osgDB::Options::setFileCache (FileCache * fileCache) [inline]
Set the FileCache that is used to manage local storage of files downloaded from the internet.
void osgDB::Options::setFileLocationCallback (FileLocationCallback * cb) [inline]
Set the callback to use inform the DatabasePager whether a file is located on local or remote file system.
void osgDB::Options::setFindFileCallback (FindFileCallback * cb) [inline]
Set the find callback to use in place of the default findFile calls.
void osgDB::Options::setObjectCacheHint (CacheHintOptions useObjectCache) [inline]
Set whether the Registry::ObjectCache should be used by default.
void osgDB::Options::setOptionString (const std::string & str) [inline]
Set the general Options string.
void osgDB::Options::setPluginData (const std::string & s, void * v) const [inline]
Sets a plugindata value PluginData with a string.
void osgDB::Options::setPluginStringData (const std::string & s, const std::string & v) const [inline]
Sets a plugindata value PluginData with a string.
void osgDB::Options::setPrecisionHint (PrecisionHint hint) [inline]
Set which geometry attributes plugins should import at double precision.
void osgDB::Options::setReadFileCallback (ReadFileCallback * cb) [inline]
Set the read callback to use in place of the default readFile calls.
void osgDB::Options::setTerrain (osg::observer_ptr< osg::Node > & terrain) [inline]
Set the terrain observer_ptr, use to decorate any osgTerrain subgraphs.
void osgDB::Options::setWriteFileCallback (WriteFileCallback * cb) [inline]
Set the callback to use in place of the default writeFile calls.
Member Data Documentation
osg::ref_ptr<AuthenticationMap> osgDB::Options::_authenticationMap [protected]
BuildKdTreesHint osgDB::Options::_buildKdTreesHint [protected]
FilePathList osgDB::Options::_databasePaths [protected]
osg::ref_ptr<FileCache> osgDB::Options::_fileCache [protected]
osg::ref_ptr<FileLocationCallback> osgDB::Options::_fileLocationCallback [protected]
osg::ref_ptr<FindFileCallback> osgDB::Options::_findFileCallback [protected]
CacheHintOptions osgDB::Options::_objectCacheHint [protected]
PluginDataMap osgDB::Options::_pluginData [mutable, protected]
PluginStringDataMap osgDB::Options::_pluginStringData [mutable, protected]
PrecisionHint osgDB::Options::_precisionHint [protected]
osg::ref_ptr<ReadFileCallback> osgDB::Options::_readFileCallback [protected]
std::string osgDB::Options::_str [protected]
osg::observer_ptr<osg::Node> osgDB::Options::_terrain [protected]
osg::ref_ptr<WriteFileCallback> osgDB::Options::_writeFileCallback [protected]
The documentation for this class was generated from the following file:
osgDB/Options
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.