OpenSceneGraph: osg::Object Class Reference
osg::Object Class Reference
Base class/standard interface for objects which require IO support, cloning and reference counting.
Inherits osg::Referenced.
Inherited by osg::AnimationPath [virtual], osg::AudioSink, osg::AudioStream, osg::BufferData, osg::BufferData::ModifiedCallback [virtual], osg::BufferObject, osg::Camera::DrawCallback [virtual], osg::ConvexPlanarOccluder, osg::Drawable, osg::Drawable::ComputeBoundingBoxCallback, osg::Drawable::CullCallback [virtual], osg::Drawable::DrawCallback [virtual], osg::Drawable::EventCallback [virtual], osg::Drawable::UpdateCallback [virtual], osg::EllipsoidModel, osg::GraphicsContext, osg::Node, osg::Node::ComputeBoundingSphereCallback, osg::NodeCallback [virtual], osg::Program::ProgramBinary, osg::RefMatrixd, osg::RefMatrixf, osg::RenderBuffer, osg::Shader, osg::ShaderBinary, osg::ShaderComponent, osg::ShaderComposer, osg::Shape, osg::StateAttribute, osg::StateAttributeCallback [virtual], osg::StateSet, osg::StateSet::Callback [virtual], osg::TessellationHints, osg::TransferFunction, osg::Uniform, osg::Uniform::Callback [virtual], osg::UserDataContainer, osg::ValueObject, osg::View [virtual], osgAnimation::Action, osgAnimation::Action::Callback, osgAnimation::Animation, osgAnimation::AnimationUpdateCallbackBase [virtual], osgAnimation::StackedTransformElement, osgAnimation::VertexInfluenceMap, osgDB::DatabaseRevision, osgDB::DatabaseRevisions, osgDB::FileList, osgDB::ImageProcessor, osgDB::Options, osgDB::ReaderWriter, osgGA::GUIEventAdapter, osgManipulator::DraggerCallback [virtual], osgParticle::Counter, osgParticle::Interpolator, osgParticle::Operator, osgParticle::Placer, osgParticle::Shooter, osgShadow::ShadowTechnique, osgSim::BlinkSequence, osgSim::LightPointSystem, osgSim::ObjectRecordData, osgSim::Sector, osgSim::SequenceGroup, osgSim::ShapeAttributeList, osgTerrain::Layer, osgTerrain::Locator, osgTerrain::TerrainTechnique, osgText::Bevel, osgText::Font, osgText::Style, osgUtil::PositionalStateContainer, osgUtil::RenderBin, osgUtil::SceneView, osgViewer::ViewerBase [virtual], osgVolume::ImageDetails, osgVolume::Layer, osgVolume::Locator, osgVolume::Locator::LocatorCallback [virtual], osgVolume::Property, osgVolume::VolumeTechnique, osgWidget::BrowserManager, osgWidget::Style, and osgWidget::StyleManager.
Public Types
enum DataVariance { DYNAMIC, STATIC, UNSPECIFIED }
Public Member Functions
Object ()
Construct an object.
Object (bool threadSafeRefUnref)
Object (const Object &, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
Copy constructor, optional CopyOp object can be used to control shallow vs deep copying of dynamic data.
virtual Object * cloneType () const =0
Clone the type of an object, with Object* return type.
virtual Object * clone (const CopyOp &) const =0
Clone an object, with Object* return type.
virtual bool isSameKindAs (const Object *) const
virtual const char * libraryName () const =0
return the name of the object's library.
virtual const char * className () const =0
return the name of the object's class type.
virtual void setThreadSafeRefUnref (bool threadSafe)
Set whether to use a mutex to ensure ref() and unref() are thread safe.
virtual void setName (const std::string &name)
Set the name of object using C++ style string.
void setName (const char *name)
Set the name of object using a C style string.
const std::string & getName () const
Get the name of object.
void setDataVariance (DataVariance dv)
Set the data variance of this object.
DataVariance getDataVariance () const
Get the data variance of this object.
virtual void computeDataVariance ()
Compute the DataVariance based on an assessment of callback etc.
void setUserDataContainer (osg::UserDataContainer *udc)
set the UserDataContainer object.
osg::UserDataContainer * getUserDataContainer ()
get the UserDataContainer attached to this object.
const osg::UserDataContainer * getUserDataContainer () const
get the const UserDataContainer attached to this object.
osg::UserDataContainer * getOrCreateUserDataContainer ()
Convinience method that returns the UserDataContainer, and if one doesn't already exist creates and assigns a DefaultUserDataContainer to the Object and then return this new UserDataContainer.
virtual void setUserData (Referenced *obj)
Set user data, data must be subclassed from Referenced to allow automatic memory handling.
virtual Referenced * getUserData ()
Get user data.
virtual const Referenced * getUserData () const
Get const user data.
template<typename T >
bool getUserValue (const std::string &name, T &value) const
Convinience method that casts the named UserObject to osg::TemplateValueObject<T> and gets the value.
template<typename T >
void setUserValue (const std::string &name, const T &value)
Convinience method that creates the osg::TemplateValueObject<T> to store the specified value and adds it as a named UserObject.
virtual void resizeGLObjectBuffers (unsigned int)
Resize any per context GLObject buffers to specified size.
virtual void releaseGLObjects (osg::State *=0) const
If State is non-zero, this function releases any associated OpenGL objects for the specified graphics context.
Protected Member Functions
virtual ~Object ()
Object destructor.
Protected Attributes
std::string _name
DataVariance _dataVariance
osg::UserDataContainer * _userDataContainer
Detailed Description
Base class/standard interface for objects which require IO support, cloning and reference counting.
Based on GOF Composite, Prototype and Template Method patterns.
Member Enumeration Documentation
enum osg::Object::DataVariance
Enumerator:
DYNAMIC
STATIC
UNSPECIFIED
Constructor & Destructor Documentation
osg::Object::Object () [inline]
Construct an object.
Note Object is a pure virtual base class and therefore cannot be constructed on its own, only derived classes which override the clone and className methods are concrete classes and can be constructed.
osg::Object::Object (bool threadSafeRefUnref) [inline, explicit]
osg::Object::Object (const Object & , const CopyOp & copyop = CopyOp::SHALLOW_COPY)
Copy constructor, optional CopyOp object can be used to control shallow vs deep copying of dynamic data.
virtual osg::Object::~Object () [protected, virtual]
Object destructor.
Note, is protected so that Objects cannot be deleted other than by being dereferenced and the reference count being zero (see osg::Referenced), preventing the deletion of nodes which are still in use. This also means that Nodes cannot be created on stack i.e Node node will not compile, forcing all nodes to be created on the heap i.e Node* node = new Node().
Member Function Documentation
virtual const char* osg::Object::className () const [pure virtual]
return the name of the object's class type.
Must be defined by derived classes.
Implemented in osg::Array, osg::AudioSink, osg::AudioStream, osg::AutoTransform, osg::BufferObject, osg::BufferData, osg::ClipPlane, osg::Drawable, osg::DrawPixels, osg::Geometry, osg::GraphicsContext, osg::Hint, osg::Image, osg::ImageSequence, osg::ImageStream, osg::Light, osg::Node, osg::PrimitiveSet, osg::DrawArrays, osg::ShaderAttribute, osg::Shape, osg::ShapeDrawable, osg::StateAttribute, osg::StateSet, osg::Texture, osg::UserDataContainer, osg::TemplateValueObject< T >, osgDB::Archive, osgFX::Effect, osgGA::AnimationPathManipulator, osgGA::CameraManipulator, osgGA::CameraViewSwitchManipulator, osgGA::DriveManipulator, osgGA::KeySwitchMatrixManipulator, osgGA::SphericalManipulator, osgGA::StandardManipulator, osgGA::StateSetManipulator, osgGA::UFOManipulator, osgParticle::CenteredPlacer, osgParticle::Counter, osgParticle::Emitter, osgParticle::Interpolator, osgParticle::Operator, osgParticle::ParticleEffect, osgParticle::ParticleProcessor, osgParticle::Placer, osgParticle::PrecipitationEffect, osgParticle::Program, osgParticle::Shooter, osgParticle::VariableRateCounter, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgSim::Sector, osgText::Font, osgText::GlyphTexture, osgText::Text, osgText::TextBase, osgUtil::PositionalStateContainer, osgUtil::RenderBin, osgUtil::RenderStage, and osgAnimation::MorphGeometry.
virtual Object* osg::Object::clone (const CopyOp &) const [pure virtual]
Clone an object, with Object* return type.
Must be defined by derived classes.
Implemented in osg::AutoTransform, osg::ClipPlane, osg::DrawPixels, osg::Geometry, osg::GraphicsContext, osg::Hint, osg::Image, osg::ImageSequence, osg::ImageStream, osg::Light, osg::Node, osg::DrawArrays, osg::ShaderAttribute, osg::Shape, osg::ShapeDrawable, osg::StateAttribute, osg::StateSet, osg::Texture, osg::TemplateValueObject< T >, osgManipulator::AntiSquish, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::Font, osgText::Text, osgUtil::PositionalStateContainer, osgUtil::RenderBin, osgUtil::RenderStage, and osgAnimation::MorphGeometry.
virtual Object* osg::Object::cloneType () const [pure virtual]
Clone the type of an object, with Object* return type.
Must be defined by derived classes.
Implemented in osg::AutoTransform, osg::ClipPlane, osg::DrawPixels, osg::Geometry, osg::GraphicsContext, osg::Hint, osg::Image, osg::ImageSequence, osg::ImageStream, osg::Light, osg::Node, osg::DrawArrays, osg::ShaderAttribute, osg::Shape, osg::ShapeDrawable, osg::StateAttribute, osg::StateSet, osg::Texture, osg::TemplateValueObject< T >, osgManipulator::AntiSquish, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::Font, osgText::Text, osgUtil::PositionalStateContainer, osgUtil::RenderBin, osgUtil::RenderStage, and osgAnimation::MorphGeometry.
virtual void osg::Object::computeDataVariance () [inline, virtual]
Compute the DataVariance based on an assessment of callback etc.
Reimplemented in osg::Drawable, and osg::StateSet.
DataVariance osg::Object::getDataVariance () const [inline]
Get the data variance of this object.
Referenced by osgUtil::RenderLeaf::RenderLeaf(), and osgUtil::StateGraph::StateGraph().
const std::string& osg::Object::getName () const [inline]
Get the name of object.
Reimplemented in osgAnimation::AnimationUpdateCallback< T >, osgAnimation::AnimationUpdateCallback< osg::NodeCallback >, and osgAnimation::AnimationUpdateCallback< osg::StateAttributeCallback >.
Referenced by osgTerrain::CompositeLayer::addLayer(), osg::State::applyShaderCompositionUniform(), and osgAnimation::RigGeometry::UpdateVertex::update().
osg::UserDataContainer* osg::Object::getOrCreateUserDataContainer ()
Convinience method that returns the UserDataContainer, and if one doesn't already exist creates and assigns a DefaultUserDataContainer to the Object and then return this new UserDataContainer.
Referenced by setUserValue().
virtual const Referenced* osg::Object::getUserData () const [virtual]
Get const user data.
Reimplemented in osg::UserDataContainer, and osg::DefaultUserDataContainer.
virtual Referenced* osg::Object::getUserData () [virtual]
Get user data.
Reimplemented in osg::UserDataContainer, and osg::DefaultUserDataContainer.
Referenced by osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
osg::UserDataContainer* osg::Object::getUserDataContainer () [inline]
get the UserDataContainer attached to this object.
const osg::UserDataContainer* osg::Object::getUserDataContainer () const [inline]
get the const UserDataContainer attached to this object.
template<typename T > BoolValueObject UCharValueObject UShortValueObject UIntValueObject DoubleValueObject Vec3fValueObject Vec2dValueObject Vec4dValueObject PlaneValueObject MatrixdValueObject bool osg::Object::getUserValue (const std::string & name, T & value) const
Convinience method that casts the named UserObject to osg::TemplateValueObject<T> and gets the value.
provide implementation of osg::Object::getUserValue(..) template
To use this template method you need to include the osg/ValueObject header.
References osg::UserDataContainer::getUserObject().
virtual bool osg::Object::isSameKindAs (const Object *) const [inline, virtual]
Reimplemented in osg::Array, osg::IndexArray, osg::AudioStream, osg::AutoTransform, osg::BufferObject, osg::BufferData, osg::ClipPlane, osg::Drawable, osg::DrawPixels, osg::Geometry, osg::GraphicsContext, osg::Hint, osg::Image, osg::ImageSequence, osg::ImageStream, osg::Light, osg::Node, osg::PrimitiveSet, osg::DrawArrays, osg::ShaderAttribute, osg::Shape, osg::ShapeDrawable, osg::StateAttribute, osg::StateSet, osg::Texture, osg::UserDataContainer, osg::TemplateValueObject< T >, osgFX::Effect, osgManipulator::AntiSquish, osgParticle::CenteredPlacer, osgParticle::Counter, osgParticle::Emitter, osgParticle::Interpolator, osgParticle::Operator, osgParticle::ParticleEffect, osgParticle::ParticleProcessor, osgParticle::Placer, osgParticle::PrecipitationEffect, osgParticle::Program, osgParticle::Shooter, osgParticle::VariableRateCounter, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgSim::Sector, osgText::Font, osgText::Text, osgText::TextBase, osgUtil::PositionalStateContainer, osgUtil::RenderBin, osgUtil::RenderStage, and osgAnimation::MorphGeometry.
virtual const char* osg::Object::libraryName () const [pure virtual]
return the name of the object's library.
Must be defined by derived classes. The OpenSceneGraph convention is that the namespace of a library is the same as the library name.
Implemented in osg::Array, osg::AudioSink, osg::AudioStream, osg::AutoTransform, osg::BufferObject, osg::BufferData, osg::ClipPlane, osg::Drawable, osg::DrawPixels, osg::Geometry, osg::GraphicsContext, osg::Hint, osg::Image, osg::ImageSequence, osg::ImageStream, osg::Light, osg::Node, osg::PrimitiveSet, osg::DrawArrays, osg::ShaderAttribute, osg::Shape, osg::ShapeDrawable, osg::StateAttribute, osg::StateSet, osg::Texture, osg::UserDataContainer, osg::TemplateValueObject< T >, osgDB::Archive, osgFX::Effect, osgParticle::CenteredPlacer, osgParticle::Counter, osgParticle::Emitter, osgParticle::Interpolator, osgParticle::Operator, osgParticle::ParticleEffect, osgParticle::ParticleProcessor, osgParticle::Placer, osgParticle::PrecipitationEffect, osgParticle::Program, osgParticle::Shooter, osgParticle::VariableRateCounter, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgSim::Sector, osgText::Font, osgText::Text, osgText::TextBase, osgUtil::PositionalStateContainer, osgUtil::RenderBin, and osgAnimation::MorphGeometry.
virtual void osg::Object::releaseGLObjects (osg::State * = 0) const [inline, virtual]
If State is non-zero, this function releases any associated OpenGL objects for the specified graphics context.
Otherwise, releases OpenGL objects for all graphics contexts.
Reimplemented in osg::BufferObject, osg::BufferData, osg::Drawable, osg::FragmentProgram, osg::RenderBuffer, osg::FrameBufferObject, osg::Geode, osg::Geometry, osg::Group, osg::Node, osg::QueryGeometry, osg::OcclusionQueryNode, osg::Program, osg::Shader, osg::ShaderComponent, osg::ShaderAttribute, osg::StateAttribute, osg::StateSet, osg::Texture, osg::VertexProgram, osgSim::OverlayNode, osgTerrain::TerrainTile, osgText::Font, osgText::Text, osgText::Text3D, osgText::TextBase, osgUtil::RenderBin, and osgUtil::RenderStage.
virtual void osg::Object::resizeGLObjectBuffers (unsigned int) [inline, virtual]
Resize any per context GLObject buffers to specified size.
Reimplemented in osg::BufferObject, osg::BufferData, osg::PixelDataBufferObject, osg::Drawable, osg::FragmentProgram, osg::RenderBuffer, osg::FrameBufferObject, osg::Geode, osg::Geometry, osg::Group, osg::Node, osg::Program, osg::Shader, osg::ShaderComponent, osg::ShaderAttribute, osg::StateAttribute, osg::StateSet, osg::Texture, osg::VertexProgram, osgSim::OverlayNode, osgText::Font, osgText::GlyphTexture, osgText::Text, osgText::Text3D, and osgText::TextBase.
void osg::Object::setDataVariance (DataVariance dv) [inline]
Set the data variance of this object.
Can be set to either STATIC for values that do not change over the lifetime of the object, or DYNAMIC for values that vary over the lifetime of the object. The DataVariance value can be used by routines such as optimization codes that wish to share static data. UNSPECIFIED is used to specify that the DataVariance hasn't been set yet.
void osg::Object::setName (const char * name) [inline]
Set the name of object using a C style string.
virtual void osg::Object::setName (const std::string & name) [inline, virtual]
Set the name of object using C++ style string.
Reimplemented in osg::Uniform.
Referenced by osgAnimation::AnimationUpdateCallback< osg::StateAttributeCallback >::AnimationUpdateCallback(), and osg::ValueObject::ValueObject().
virtual void osg::Object::setThreadSafeRefUnref (bool threadSafe) [virtual]
Set whether to use a mutex to ensure ref() and unref() are thread safe.
Reimplemented from osg::Referenced.
Reimplemented in osg::Drawable, osg::Geode, osg::Group, osg::LightSource, osg::Node, osg::Program, osg::StateSet, osg::TexGenNode, osgSim::OverlayNode, osgText::Font, osgText::GlyphTexture, osgText::Text, osgText::Text3D, and osgText::TextBase.
virtual void osg::Object::setUserData (Referenced * obj) [virtual]
Set user data, data must be subclassed from Referenced to allow automatic memory handling.
If your own data isn't directly subclassed from Referenced then create an adapter object which points to your own object and handles the memory addressing.
Reimplemented in osg::UserDataContainer, and osg::DefaultUserDataContainer.
void osg::Object::setUserDataContainer (osg::UserDataContainer * udc)
set the UserDataContainer object.
template<typename T > void osg::Object::setUserValue (const std::string & name, const T & value)
Convinience method that creates the osg::TemplateValueObject<T> to store the specified value and adds it as a named UserObject.
provide implementation of osg::Object::setUserValue(..) template.
To use this template method you need to include the osg/ValueObject header.
References _userDataContainer, osg::UserDataContainer::addUserObject(), getOrCreateUserDataContainer(), osg::UserDataContainer::getUserObjectIndex(), and osg::UserDataContainer::setUserObject().
Member Data Documentation
DataVariance osg::Object::_dataVariance [protected]
std::string osg::Object::_name [protected]
Referenced by osgWidget::NotifyWidget::focus(), osgWidget::NotifyWidget::keyPress(), osgWidget::NotifyWidget::keyRelease(), osgWidget::NotifyWidget::mouseDrag(), osgWidget::NotifyWidget::mouseEnter(), osgWidget::NotifyWidget::mouseLeave(), osgWidget::NotifyWidget::mouseOver(), osgWidget::NotifyWidget::mousePush(), osgWidget::NotifyWidget::mouseRelease(), osgWidget::NotifyWidget::mouseScroll(), and osgWidget::NotifyWidget::unfocus().
osg::UserDataContainer* osg::Object::_userDataContainer [protected]
Referenced by setUserValue().
The documentation for this class was generated from the following files:
osg/Object
osg/ValueObject
Generated at Mon Aug 1 2011 15:38:46 for the OpenSceneGraph by doxygen 1.7.1.