OpenSceneGraph: osgVolume::PropertyVisitor Class Reference
osgVolume::PropertyVisitor Class Reference
Public Member Functions
PropertyVisitor (bool traverseOnlyActiveChildren=true)
virtual ~PropertyVisitor ()
virtual void apply (Property &)
virtual void apply (CompositeProperty &)
virtual void apply (SwitchProperty &)
virtual void apply (TransferFunctionProperty &)
virtual void apply (ScalarProperty &)
virtual void apply (IsoSurfaceProperty &)
virtual void apply (AlphaFuncProperty &)
virtual void apply (MaximumIntensityProjectionProperty &)
virtual void apply (LightingProperty &)
virtual void apply (SampleDensityProperty &)
virtual void apply (SampleDensityWhenMovingProperty &)
virtual void apply (TransparencyProperty &)
Public Attributes
bool _traverseOnlyActiveChildren
Constructor & Destructor Documentation
osgVolume::PropertyVisitor::PropertyVisitor (bool traverseOnlyActiveChildren = true)
virtual osgVolume::PropertyVisitor::~PropertyVisitor () [inline, virtual]
Member Function Documentation
virtual void osgVolume::PropertyVisitor::apply (Property &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
Referenced by osgVolume::TransparencyProperty::accept(), osgVolume::SampleDensityWhenMovingProperty::accept(), osgVolume::SampleDensityProperty::accept(), osgVolume::LightingProperty::accept(), osgVolume::MaximumIntensityProjectionProperty::accept(), osgVolume::AlphaFuncProperty::accept(), osgVolume::IsoSurfaceProperty::accept(), osgVolume::ScalarProperty::accept(), osgVolume::TransferFunctionProperty::accept(), osgVolume::SwitchProperty::accept(), osgVolume::CompositeProperty::accept(), and osgVolume::Property::accept().
virtual void osgVolume::PropertyVisitor::apply (TransparencyProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (SampleDensityWhenMovingProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (SampleDensityProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (LightingProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (MaximumIntensityProjectionProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (AlphaFuncProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (IsoSurfaceProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (ScalarProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (TransferFunctionProperty &) [inline, virtual]
Reimplemented in osgVolume::CollectPropertiesVisitor.
virtual void osgVolume::PropertyVisitor::apply (SwitchProperty &) [virtual]
virtual void osgVolume::PropertyVisitor::apply (CompositeProperty &) [virtual]
Member Data Documentation
bool osgVolume::PropertyVisitor::_traverseOnlyActiveChildren
The documentation for this class was generated from the following file:
osgVolume/Property
Generated at Mon Aug 1 2011 15:38:50 for the OpenSceneGraph by doxygen 1.7.1.