OpenSceneGraph: osgDB::RegisterImageProcessorProxy< T > Class Template Reference
osgDB::RegisterImageProcessorProxy< T > Class Template Reference
Proxy class for automatic registration of reader/writers with the Registry.
Public Member Functions
RegisterImageProcessorProxy ()
~RegisterImageProcessorProxy ()
T * get ()
Protected Attributes
osg::ref_ptr< T > _rw
Detailed Description
template<class T>
class osgDB::RegisterImageProcessorProxy< T >
Proxy class for automatic registration of reader/writers with the Registry.
Constructor & Destructor Documentation
template<class T> osgDB::RegisterImageProcessorProxy< T >::RegisterImageProcessorProxy () [inline]
References osgDB::RegisterImageProcessorProxy< T >::_rw, osgDB::Registry::addImageProcessor(), and osgDB::Registry::instance().
template<class T> osgDB::RegisterImageProcessorProxy< T >::~RegisterImageProcessorProxy () [inline]
References osgDB::RegisterImageProcessorProxy< T >::_rw, osgDB::Registry::instance(), and osgDB::Registry::removeImageProcessor().
Member Function Documentation
template<class T> T* osgDB::RegisterImageProcessorProxy< T >::get () [inline]
References osgDB::RegisterImageProcessorProxy< T >::_rw.
Member Data Documentation
template<class T> osg::ref_ptr<T> osgDB::RegisterImageProcessorProxy< T >::_rw [protected]
Referenced by osgDB::RegisterImageProcessorProxy< T >::get(), osgDB::RegisterImageProcessorProxy< T >::RegisterImageProcessorProxy(), and osgDB::RegisterImageProcessorProxy< T >::~RegisterImageProcessorProxy().
The documentation for this class was generated from the following file:
osgDB/Registry
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.