OpenSceneGraph: osgDB::PropByRefSerializer< C, P > Class Template Reference
osgDB::PropByRefSerializer< C, P > Class Template Reference
Public Types
typedef TemplateSerializer< P > ParentType
typedef const P & CP
typedef CP(C::* Getter)() const
typedef void(C::* Setter)(CP)
Public Member Functions
PropByRefSerializer (const char *name, CP def, Getter gf, Setter sf)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
Public Attributes
Getter _getter
Setter _setter
template<typename C, typename P>
class osgDB::PropByRefSerializer< C, P >
Member Typedef Documentation
template<typename C , typename P > typedef const P& osgDB::PropByRefSerializer< C, P >::CP
template<typename C , typename P > typedef CP(C::* osgDB::PropByRefSerializer< C, P >::Getter)() const
template<typename C , typename P > typedef TemplateSerializer<P> osgDB::PropByRefSerializer< C, P >::ParentType
template<typename C , typename P > typedef void(C::* osgDB::PropByRefSerializer< C, P >::Setter)(CP)
Constructor & Destructor Documentation
template<typename C , typename P > osgDB::PropByRefSerializer< C, P >::PropByRefSerializer (const char * name, CP def, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C , typename P > virtual bool osgDB::PropByRefSerializer< C, P >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P >.
References osgDB::TemplateSerializer< P >::_defaultValue, osgDB::TemplateSerializer< P >::_name, osgDB::PropByRefSerializer< C, P >::_setter, osgDB::InputStream::isBinary(), and osgDB::InputStream::matchString().
template<typename C , typename P > virtual bool osgDB::PropByRefSerializer< C, P >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< P >.
References osgDB::TemplateSerializer< P >::_defaultValue, osgDB::PropByRefSerializer< C, P >::_getter, osgDB::TemplateSerializer< P >::_name, osgDB::OutputStream::isBinary(), and PROPERTY.
Member Data Documentation
template<typename C , typename P > Getter osgDB::PropByRefSerializer< C, P >::_getter
Referenced by osgDB::PropByRefSerializer< C, P >::write().
template<typename C , typename P > Setter osgDB::PropByRefSerializer< C, P >::_setter
Referenced by osgDB::PropByRefSerializer< C, P >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.