OpenSceneGraph: osg::Texture2D::SubloadCallback Class Reference
osg::Texture2D::SubloadCallback Class Reference
Public Member Functions
virtual bool textureObjectValid (const Texture2D &texture, State &state) const
virtual TextureObject * generateTextureObject (const Texture2D &texture, State &state) const
virtual void load (const Texture2D &texture, State &state) const =0
virtual void subload (const Texture2D &texture, State &state) const =0
Member Function Documentation
virtual TextureObject* osg::Texture2D::SubloadCallback::generateTextureObject (const Texture2D & texture, State & state) const [inline, virtual]
References osg::Texture::generateTextureObject(), and osg::State::getContextID().
virtual void osg::Texture2D::SubloadCallback::load (const Texture2D & texture, State & state) const [pure virtual]
virtual void osg::Texture2D::SubloadCallback::subload (const Texture2D & texture, State & state) const [pure virtual]
virtual bool osg::Texture2D::SubloadCallback::textureObjectValid (const Texture2D & texture, State & state) const [inline, virtual]
References osg::Texture2D::textureObjectValid().
The documentation for this class was generated from the following file:
osg/Texture2D
Generated at Mon Aug 1 2011 15:38:46 for the OpenSceneGraph by doxygen 1.7.1.