OpenSceneGraph: osgParticle::SinkOperator Class Reference
osgParticle::SinkOperator Class Reference
A sink operator kills particles if positions or velocities inside/outside the specified domain.
Public Types
enum SinkTarget { SINK_POSITION, SINK_VELOCITY, SINK_ANGULAR_VELOCITY }
enum SinkStrategy { SINK_INSIDE, SINK_OUTSIDE }
Public Member Functions
SinkOperator ()
SinkOperator (const SinkOperator &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgParticle, SinkOperator)
void setSinkTarget (SinkTarget so)
Set the sink strategy.
SinkTarget getSinkTarget () const
Get the sink strategy.
void setSinkStrategy (SinkStrategy ss)
Set the sink strategy.
SinkStrategy getSinkStrategy () const
Get the sink strategy.
void beginOperate (Program *prg)
Perform some initializations. Do not call this method manually.
Protected Member Functions
virtual ~SinkOperator ()
SinkOperator & operator= (const SinkOperator &)
virtual void handlePoint (const Domain &domain, Particle *P, double dt)
virtual void handleLineSegment (const Domain &domain, Particle *P, double dt)
virtual void handleTriangle (const Domain &domain, Particle *P, double dt)
virtual void handleRectangle (const Domain &domain, Particle *P, double dt)
virtual void handlePlane (const Domain &domain, Particle *P, double dt)
virtual void handleSphere (const Domain &domain, Particle *P, double dt)
virtual void handleBox (const Domain &domain, Particle *P, double dt)
virtual void handleDisk (const Domain &domain, Particle *P, double dt)
const osg::Vec3 & getValue (Particle *P)
void kill (Particle *P, bool insideDomain)
Protected Attributes
SinkTarget _sinkTarget
SinkStrategy _sinkStrategy
Detailed Description
A sink operator kills particles if positions or velocities inside/outside the specified domain.
Refer to David McAllister's Particle System API (http://www.particlesystems.org)
Member Enumeration Documentation
enum osgParticle::SinkOperator::SinkStrategy
Enumerator:
SINK_INSIDE
SINK_OUTSIDE
enum osgParticle::SinkOperator::SinkTarget
Enumerator:
SINK_POSITION
SINK_VELOCITY
SINK_ANGULAR_VELOCITY
Constructor & Destructor Documentation
osgParticle::SinkOperator::SinkOperator () [inline]
osgParticle::SinkOperator::SinkOperator (const SinkOperator & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::SinkOperator::~SinkOperator () [inline, protected, virtual]
Member Function Documentation
void osgParticle::SinkOperator::beginOperate (Program * prg) [virtual]
Perform some initializations. Do not call this method manually.
Reimplemented from osgParticle::DomainOperator.
SinkStrategy osgParticle::SinkOperator::getSinkStrategy () const [inline]
Get the sink strategy.
SinkTarget osgParticle::SinkOperator::getSinkTarget () const [inline]
Get the sink strategy.
const osg::Vec3 & osgParticle::SinkOperator::getValue (Particle * P) [inline, protected]
References _sinkTarget, osgParticle::Particle::getAngularVelocity(), osgParticle::Particle::getPosition(), osgParticle::Particle::getVelocity(), SINK_ANGULAR_VELOCITY, SINK_POSITION, and SINK_VELOCITY.
virtual void osgParticle::SinkOperator::handleBox (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handleDisk (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handleLineSegment (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handlePlane (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handlePoint (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handleRectangle (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handleSphere (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
virtual void osgParticle::SinkOperator::handleTriangle (const Domain & domain, Particle * P, double dt) [protected, virtual]
Reimplemented from osgParticle::DomainOperator.
void osgParticle::SinkOperator::kill (Particle * P, bool insideDomain) [inline, protected]
References _sinkStrategy, osgParticle::Particle::kill(), and SINK_INSIDE.
osgParticle::SinkOperator::META_Object (osgParticle , SinkOperator)
SinkOperator& osgParticle::SinkOperator::operator= (const SinkOperator &) [inline, protected]
void osgParticle::SinkOperator::setSinkStrategy (SinkStrategy ss) [inline]
Set the sink strategy.
void osgParticle::SinkOperator::setSinkTarget (SinkTarget so) [inline]
Set the sink strategy.
Member Data Documentation
SinkStrategy osgParticle::SinkOperator::_sinkStrategy [protected]
Referenced by kill().
SinkTarget osgParticle::SinkOperator::_sinkTarget [protected]
Referenced by getValue().
The documentation for this class was generated from the following file:
osgParticle/SinkOperator
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.