OpenSceneGraph: osgDB::StringSerializer< C > Class Template Reference
osgDB::StringSerializer< C > Class Template Reference
Public Types
typedef TemplateSerializer
< std::string > ParentType
typedef const std::string &(C::* Getter)() const
typedef void(C::* Setter)(const std::string &)
Public Member Functions
StringSerializer (const char *name, const std::string &def, Getter gf, Setter sf)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
Public Attributes
Getter _getter
Setter _setter
template<typename C>
class osgDB::StringSerializer< C >
Member Typedef Documentation
template<typename C > typedef const std::string&(C::* osgDB::StringSerializer< C >::Getter)() const
template<typename C > typedef TemplateSerializer<std::string> osgDB::StringSerializer< C >::ParentType
template<typename C > typedef void(C::* osgDB::StringSerializer< C >::Setter)(const std::string &)
Constructor & Destructor Documentation
template<typename C > osgDB::StringSerializer< C >::StringSerializer (const char * name, const std::string & def, Getter gf, Setter sf) [inline]
Member Function Documentation
template<typename C > virtual bool osgDB::StringSerializer< C >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< std::string >.
References osgDB::TemplateSerializer< std::string >::_defaultValue, osgDB::TemplateSerializer< std::string >::_name, osgDB::StringSerializer< C >::_setter, osgDB::InputStream::isBinary(), osgDB::InputStream::matchString(), and osgDB::InputStream::readWrappedString().
template<typename C > virtual bool osgDB::StringSerializer< C >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::TemplateSerializer< std::string >.
References osgDB::TemplateSerializer< std::string >::_defaultValue, osgDB::StringSerializer< C >::_getter, osgDB::TemplateSerializer< std::string >::_name, osgDB::OutputStream::isBinary(), PROPERTY, and osgDB::OutputStream::writeWrappedString().
Member Data Documentation
template<typename C > Getter osgDB::StringSerializer< C >::_getter
Referenced by osgDB::StringSerializer< C >::write().
template<typename C > Setter osgDB::StringSerializer< C >::_setter
Referenced by osgDB::StringSerializer< C >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.