OpenSceneGraph: osgAnimation::TemplateChannel< SamplerType > Class Template Reference
osgAnimation::TemplateChannel< SamplerType > Class Template Reference
Public Types
typedef SamplerType::UsingType UsingType
typedef TemplateTarget< UsingType > TargetType
typedef
TemplateKeyframeContainer
< typename
SamplerType::KeyframeType > KeyframeContainerType
Public Member Functions
Channel * clone () const
TemplateChannel (const TemplateChannel &channel)
TemplateChannel (SamplerType *s=0, TargetType *target=0)
virtual bool createKeyframeContainerFromTargetValue ()
virtual ~TemplateChannel ()
virtual void update (double time, float weight, int priority)
virtual void reset ()
virtual Target * getTarget ()
virtual bool setTarget (Target *target)
SamplerType * getOrCreateSampler ()
Sampler * getSampler ()
const Sampler * getSampler () const
SamplerType * getSamplerTyped ()
const SamplerType * getSamplerTyped () const
void setSampler (SamplerType *sampler)
TargetType * getTargetTyped ()
const TargetType * getTargetTyped () const
void setTarget (TargetType *target)
virtual double getStartTime () const
virtual double getEndTime () const
Protected Attributes
osg::ref_ptr< TargetType > _target
osg::ref_ptr< SamplerType > _sampler
template<typename SamplerType>
class osgAnimation::TemplateChannel< SamplerType >
Member Typedef Documentation
template<typename SamplerType> typedef TemplateKeyframeContainer<typename SamplerType::KeyframeType> osgAnimation::TemplateChannel< SamplerType >::KeyframeContainerType
template<typename SamplerType> typedef TemplateTarget<UsingType> osgAnimation::TemplateChannel< SamplerType >::TargetType
template<typename SamplerType> typedef SamplerType::UsingType osgAnimation::TemplateChannel< SamplerType >::UsingType
Constructor & Destructor Documentation
template<typename SamplerType> osgAnimation::TemplateChannel< SamplerType >::TemplateChannel (const TemplateChannel< SamplerType > & channel) [inline]
References osgAnimation::TemplateChannel< SamplerType >::_sampler, osgAnimation::TemplateChannel< SamplerType >::_target, osgAnimation::TemplateChannel< SamplerType >::getSamplerTyped(), and osgAnimation::TemplateChannel< SamplerType >::getTargetTyped().
template<typename SamplerType> osgAnimation::TemplateChannel< SamplerType >::TemplateChannel (SamplerType * s = 0, TargetType * target = 0) [inline]
References osgAnimation::TemplateChannel< SamplerType >::_sampler, and osgAnimation::TemplateChannel< SamplerType >::_target.
template<typename SamplerType> virtual osgAnimation::TemplateChannel< SamplerType >::~TemplateChannel () [inline, virtual]
Member Function Documentation
template<typename SamplerType> Channel* osgAnimation::TemplateChannel< SamplerType >::clone () const [inline, virtual]
Implements osgAnimation::Channel.
template<typename SamplerType> virtual bool osgAnimation::TemplateChannel< SamplerType >::createKeyframeContainerFromTargetValue () [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_sampler, osgAnimation::TemplateChannel< SamplerType >::_target, osgAnimation::TemplateChannel< SamplerType >::getOrCreateSampler(), and osg::ref_ptr< T >::valid().
template<typename SamplerType> virtual double osgAnimation::TemplateChannel< SamplerType >::getEndTime () const [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_sampler.
template<typename SamplerType> SamplerType* osgAnimation::TemplateChannel< SamplerType >::getOrCreateSampler () [inline]
References osgAnimation::TemplateChannel< SamplerType >::_sampler, osg::ref_ptr< T >::get(), and osg::ref_ptr< T >::valid().
Referenced by osgAnimation::TemplateChannel< SamplerType >::createKeyframeContainerFromTargetValue().
template<typename SamplerType> Sampler* osgAnimation::TemplateChannel< SamplerType >::getSampler () [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_sampler, and osg::ref_ptr< T >::get().
template<typename SamplerType> const Sampler* osgAnimation::TemplateChannel< SamplerType >::getSampler () const [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_sampler, and osg::ref_ptr< T >::get().
template<typename SamplerType> SamplerType* osgAnimation::TemplateChannel< SamplerType >::getSamplerTyped () [inline]
References osgAnimation::TemplateChannel< SamplerType >::_sampler, and osg::ref_ptr< T >::get().
Referenced by osgAnimation::TemplateChannel< SamplerType >::TemplateChannel().
template<typename SamplerType> const SamplerType* osgAnimation::TemplateChannel< SamplerType >::getSamplerTyped () const [inline]
References osgAnimation::TemplateChannel< SamplerType >::_sampler, and osg::ref_ptr< T >::get().
template<typename SamplerType> virtual double osgAnimation::TemplateChannel< SamplerType >::getStartTime () const [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_sampler.
template<typename SamplerType> virtual Target* osgAnimation::TemplateChannel< SamplerType >::getTarget () [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_target, and osg::ref_ptr< T >::get().
template<typename SamplerType> TargetType* osgAnimation::TemplateChannel< SamplerType >::getTargetTyped () [inline]
References osgAnimation::TemplateChannel< SamplerType >::_target, and osg::ref_ptr< T >::get().
Referenced by osgAnimation::TemplateChannel< SamplerType >::TemplateChannel().
template<typename SamplerType> const TargetType* osgAnimation::TemplateChannel< SamplerType >::getTargetTyped () const [inline]
References osgAnimation::TemplateChannel< SamplerType >::_target, and osg::ref_ptr< T >::get().
template<typename SamplerType> virtual void osgAnimation::TemplateChannel< SamplerType >::reset () [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_target.
template<typename SamplerType> void osgAnimation::TemplateChannel< SamplerType >::setSampler (SamplerType * sampler) [inline]
References osgAnimation::TemplateChannel< SamplerType >::_sampler.
template<typename SamplerType> void osgAnimation::TemplateChannel< SamplerType >::setTarget (TargetType * target) [inline]
References osgAnimation::TemplateChannel< SamplerType >::_target.
template<typename SamplerType> virtual bool osgAnimation::TemplateChannel< SamplerType >::setTarget (Target * target) [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_target, and osg::ref_ptr< T >::get().
template<typename SamplerType> virtual void osgAnimation::TemplateChannel< SamplerType >::update (double time, float weight, int priority) [inline, virtual]
Implements osgAnimation::Channel.
References osgAnimation::TemplateChannel< SamplerType >::_sampler, and osgAnimation::TemplateChannel< SamplerType >::_target.
Member Data Documentation
template<typename SamplerType> osg::ref_ptr<SamplerType> osgAnimation::TemplateChannel< SamplerType >::_sampler [protected]
Referenced by osgAnimation::TemplateChannel< SamplerType >::createKeyframeContainerFromTargetValue(), osgAnimation::TemplateChannel< SamplerType >::getEndTime(), osgAnimation::TemplateChannel< SamplerType >::getOrCreateSampler(), osgAnimation::TemplateChannel< SamplerType >::getSampler(), osgAnimation::TemplateChannel< SamplerType >::getSamplerTyped(), osgAnimation::TemplateChannel< SamplerType >::getStartTime(), osgAnimation::TemplateChannel< SamplerType >::setSampler(), osgAnimation::TemplateChannel< SamplerType >::TemplateChannel(), and osgAnimation::TemplateChannel< SamplerType >::update().
template<typename SamplerType> osg::ref_ptr<TargetType> osgAnimation::TemplateChannel< SamplerType >::_target [protected]
Referenced by osgAnimation::TemplateChannel< SamplerType >::createKeyframeContainerFromTargetValue(), osgAnimation::TemplateChannel< SamplerType >::getTarget(), osgAnimation::TemplateChannel< SamplerType >::getTargetTyped(), osgAnimation::TemplateChannel< SamplerType >::reset(), osgAnimation::TemplateChannel< SamplerType >::setTarget(), osgAnimation::TemplateChannel< SamplerType >::TemplateChannel(), and osgAnimation::TemplateChannel< SamplerType >::update().
The documentation for this class was generated from the following file:
osgAnimation/Channel
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.