OpenSceneGraph: osgAnimation::TemplateInterpolatorBase< TYPE, KEY > Class Template Reference
osgAnimation::TemplateInterpolatorBase< TYPE, KEY > Class Template Reference
Public Types
typedef KEY KeyframeType
typedef TYPE UsingType
Public Member Functions
TemplateInterpolatorBase ()
void reset ()
int getKeyIndexFromTime (const TemplateKeyframeContainer< KEY > &keys, double time) const
Public Attributes
int _lastKeyAccess
template<class TYPE, class KEY>
class osgAnimation::TemplateInterpolatorBase< TYPE, KEY >
Member Typedef Documentation
template<class TYPE , class KEY > typedef KEY osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::KeyframeType
template<class TYPE , class KEY > typedef TYPE osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::UsingType
Constructor & Destructor Documentation
template<class TYPE , class KEY > osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::TemplateInterpolatorBase () [inline]
Member Function Documentation
template<class TYPE , class KEY > int osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::getKeyIndexFromTime (const TemplateKeyframeContainer< KEY > & keys, double time) const [inline]
References osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::_lastKeyAccess, osgAnimation::Keyframe::getTime(), osg::notify(), osgAnimation::TemplateKeyframeContainer< T >::size(), and osg::WARN.
Referenced by osgAnimation::TemplateCubicBezierInterpolator< TYPE, KEY >::getValue(), osgAnimation::TemplateLinearPackedInterpolator< TYPE, KEY >::getValue(), osgAnimation::TemplateSphericalLinearInterpolator< TYPE, KEY >::getValue(), osgAnimation::TemplateLinearInterpolator< TYPE, KEY >::getValue(), and osgAnimation::TemplateStepInterpolator< TYPE, KEY >::getValue().
template<class TYPE , class KEY > void osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::reset () [inline]
References osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::_lastKeyAccess.
Member Data Documentation
template<class TYPE , class KEY > int osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::_lastKeyAccess [mutable]
Referenced by osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::getKeyIndexFromTime(), and osgAnimation::TemplateInterpolatorBase< TYPE, KEY >::reset().
The documentation for this class was generated from the following file:
osgAnimation/Interpolator
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.