OpenSceneGraph: osg::TemplateValueObject< T > Class Template Reference
osg::TemplateValueObject< T > Class Template Reference
Public Member Functions
TemplateValueObject ()
TemplateValueObject (const std::string &name, const T &value)
TemplateValueObject (const TemplateValueObject &rhs, const osg::CopyOp copyop=osg::CopyOp::SHALLOW_COPY)
virtual Object * cloneType () const
Clone the type of an object, with Object* return type.
virtual Object * clone (const CopyOp &copyop) const
Clone an object, with Object* return type.
virtual bool isSameKindAs (const Object *obj) const
virtual const char * libraryName () const
return the name of the object's library.
virtual const char * className () const
return the name of the object's class type.
void setValue (const T &value)
const T & getValue () const
virtual bool get (GetValueVisitor &gvv) const
virtual bool set (SetValueVisitor &svv)
Protected Attributes
T _value
Static Protected Attributes
static const char * s_TemplateValueObject_className
template<typename T>
class osg::TemplateValueObject< T >
Constructor & Destructor Documentation
template<typename T > osg::TemplateValueObject< T >::TemplateValueObject () [inline]
Referenced by osg::TemplateValueObject< T >::clone(), and osg::TemplateValueObject< T >::cloneType().
template<typename T > osg::TemplateValueObject< T >::TemplateValueObject (const std::string & name, const T & value) [inline]
template<typename T > osg::TemplateValueObject< T >::TemplateValueObject (const TemplateValueObject< T > & rhs, const osg::CopyOp copyop = osg::CopyOp::SHALLOW_COPY) [inline]
Member Function Documentation
template<typename T > virtual const char* osg::TemplateValueObject< T >::className () const [inline, virtual]
return the name of the object's class type.
Must be defined by derived classes.
Implements osg::Object.
template<typename T > virtual Object* osg::TemplateValueObject< T >::clone (const CopyOp &) const [inline, virtual]
Clone an object, with Object* return type.
Must be defined by derived classes.
Implements osg::Object.
References osg::TemplateValueObject< T >::TemplateValueObject().
template<typename T > virtual Object* osg::TemplateValueObject< T >::cloneType () const [inline, virtual]
Clone the type of an object, with Object* return type.
Must be defined by derived classes.
Implements osg::Object.
References osg::TemplateValueObject< T >::TemplateValueObject().
template<typename T > virtual bool osg::TemplateValueObject< T >::get (GetValueVisitor & gvv) const [inline, virtual]
Reimplemented from osg::ValueObject.
References osg::TemplateValueObject< T >::_value.
template<typename T > const T& osg::TemplateValueObject< T >::getValue () const [inline]
References osg::TemplateValueObject< T >::_value.
template<typename T > virtual bool osg::TemplateValueObject< T >::isSameKindAs (const Object * obj) const [inline, virtual]
Reimplemented from osg::Object.
References NULL.
template<typename T > virtual const char* osg::TemplateValueObject< T >::libraryName () const [inline, virtual]
return the name of the object's library.
Must be defined by derived classes. The OpenSceneGraph convention is that the namespace of a library is the same as the library name.
Implements osg::Object.
template<typename T > virtual bool osg::TemplateValueObject< T >::set (SetValueVisitor & svv) [inline, virtual]
Reimplemented from osg::ValueObject.
References osg::TemplateValueObject< T >::_value.
template<typename T > void osg::TemplateValueObject< T >::setValue (const T & value) [inline]
References osg::TemplateValueObject< T >::_value.
Member Data Documentation
template<typename T > T osg::TemplateValueObject< T >::_value [protected]
Referenced by osg::TemplateValueObject< T >::get(), osg::TemplateValueObject< T >::getValue(), osg::TemplateValueObject< T >::set(), and osg::TemplateValueObject< T >::setValue().
template<typename T > const char* osg::TemplateValueObject< T >::s_TemplateValueObject_className [static, protected]
The documentation for this class was generated from the following file:
osg/ValueObject
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.