OpenSceneGraph: osgDB::UserSerializer< C > Class Template Reference
osgDB::UserSerializer< C > Class Template Reference
Public Types
typedef bool(* Checker)(const C &)
typedef bool(* Reader)(InputStream &, C &)
typedef bool(* Writer)(OutputStream &, const C &)
Public Member Functions
UserSerializer (const char *name, Checker cf, Reader rf, Writer wf)
virtual bool read (InputStream &is, osg::Object &obj)
virtual bool write (OutputStream &os, const osg::Object &obj)
virtual const std::string & getName () const
Public Attributes
Reader _reader
Writer _writer
Protected Attributes
std::string _name
Checker _checker
template<typename C>
class osgDB::UserSerializer< C >
Member Typedef Documentation
template<typename C > typedef bool(* osgDB::UserSerializer< C >::Checker)(const C &)
template<typename C > typedef bool(* osgDB::UserSerializer< C >::Reader)(InputStream &, C &)
template<typename C > typedef bool(* osgDB::UserSerializer< C >::Writer)(OutputStream &, const C &)
Constructor & Destructor Documentation
template<typename C > osgDB::UserSerializer< C >::UserSerializer (const char * name, Checker cf, Reader rf, Writer wf) [inline]
Member Function Documentation
template<typename C > virtual const std::string& osgDB::UserSerializer< C >::getName () const [inline, virtual]
Implements osgDB::BaseSerializer.
References osgDB::UserSerializer< C >::_name.
template<typename C > virtual bool osgDB::UserSerializer< C >::read (InputStream & is, osg::Object & obj) [inline, virtual]
Implements osgDB::BaseSerializer.
References osgDB::UserSerializer< C >::_name, osgDB::UserSerializer< C >::_reader, osgDB::InputStream::isBinary(), and osgDB::InputStream::matchString().
template<typename C > virtual bool osgDB::UserSerializer< C >::write (OutputStream & os, const osg::Object & obj) [inline, virtual]
Implements osgDB::BaseSerializer.
References osgDB::UserSerializer< C >::_name, osgDB::UserSerializer< C >::_writer, osgDB::OutputStream::isBinary(), and PROPERTY.
Member Data Documentation
template<typename C > Checker osgDB::UserSerializer< C >::_checker [protected]
template<typename C > std::string osgDB::UserSerializer< C >::_name [protected]
Referenced by osgDB::UserSerializer< C >::getName(), osgDB::UserSerializer< C >::read(), and osgDB::UserSerializer< C >::write().
template<typename C > Reader osgDB::UserSerializer< C >::_reader
Referenced by osgDB::UserSerializer< C >::read().
template<typename C > Writer osgDB::UserSerializer< C >::_writer
Referenced by osgDB::UserSerializer< C >::write().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Mon Aug 1 2011 15:38:47 for the OpenSceneGraph by doxygen 1.7.1.