OpenSceneGraph: osgManipulator Namespace Reference
osgManipulator Namespace Reference
The osgManipulator library is a NodeKit that extends the core scene graph to support 3D interactive manipulators.
Classes
class AntiSquish
Class that performs the Anti Squish by making the scaling uniform along all axes.
class MotionCommand
Base class for motion commands that are generated by draggers.
class TranslateInLineCommand
Command for translating in a line.
class TranslateInPlaneCommand
Command for translating in a plane.
class Scale1DCommand
Command for 1D scaling.
class Scale2DCommand
Command for 2D scaling.
class ScaleUniformCommand
Command for uniform 3D scaling.
class Rotate3DCommand
Command for rotation in 3D.
class CommandManager
Deprecated.
class Constraint
class GridConstraint
Constraint to snap motion commands to a sugar cube grid.
class DraggerCallback
class DraggerTransformCallback
class PointerInfo
class Dragger
Base class for draggers.
class CompositeDragger
CompositeDragger allows to create complex draggers that are composed of a hierarchy of Draggers.
class Projector
Base class for Projectors.
class LineProjector
LineProjector projects points onto the closest point on the given line.
class PlaneProjector
PlaneProjector projects points onto the given line.
class SphereProjector
SphereProjector projects points onto the given sphere.
class SpherePlaneProjector
SpherePlaneProjector projects points onto a sphere, failing which it project onto a plane oriented to the viewing direction.
class CylinderProjector
CylinderProjector projects points onto the given cylinder.
class CylinderPlaneProjector
CylinderPlaneProjector projects points onto the given cylinder.
class RotateCylinderDragger
Dragger for performing 3D rotation on a cylinder.
class RotateSphereDragger
Dragger for performing 3D rotation on a sphere.
class Scale1DDragger
Dragger for performing 1D scaling.
class Scale2DDragger
Dragger for performing 2D scaling.
class ScaleAxisDragger
Dragger for performing scaling on all 3 axes.
class TabBoxDragger
TabBoxDragger consists of 6 TabPlaneDraggers to form a box dragger that performs translation and scaling.
class TabBoxTrackballDragger
Dragger for performing rotation in all axes.
class TabPlaneDragger
Tab plane dragger consists of a plane with tabs on it's corners and edges for scaling.
class TabPlaneTrackballDragger
Dragger for performing rotation in all axes.
class TrackballDragger
Dragger for performing rotation in all axes.
class Translate1DDragger
Dragger for performing 1D translation.
class Translate2DDragger
Dragger for performing 2D translation.
class TranslateAxisDragger
Dragger for performing translation in all three axes.
class TranslatePlaneDragger
Tab plane dragger consists of a plane with tabs on it's corners and edges for scaling.
Typedefs
typedef osg::MatrixTransform Selection
Functions
OSGMANIPULATOR_EXPORT void computeNodePathToRoot (osg::Node &node, osg::NodePath &np)
Computes the nodepath from the given node all the way upto the root.
void OSGMANIPULATOR_EXPORT setDrawableToAlwaysCull (osg::Drawable &drawable)
Culls the drawable all the time.
void OSGMANIPULATOR_EXPORT setMaterialColor (const osg::Vec4 &color, osg::Node &node)
Convenience function for setting the material color on a node.
Detailed Description
The osgManipulator library is a NodeKit that extends the core scene graph to support 3D interactive manipulators.
Typedef Documentation
typedef osg::MatrixTransform osgManipulator::Selection
Function Documentation
OSGMANIPULATOR_EXPORT void osgManipulator::computeNodePathToRoot (osg::Node & node, osg::NodePath & np)
Computes the nodepath from the given node all the way upto the root.
void OSGMANIPULATOR_EXPORT osgManipulator::setDrawableToAlwaysCull (osg::Drawable & drawable)
Culls the drawable all the time.
Used by draggers to have invisible geometry around lines and points so that they can be picked. For example, a dragger could have a line with an invisible cylinder around it to enable picking on that line.
void OSGMANIPULATOR_EXPORT osgManipulator::setMaterialColor (const osg::Vec4 & color, osg::Node & node)
Convenience function for setting the material color on a node.
Referenced by osgManipulator::Translate2DDragger::setColor(), osgManipulator::Translate1DDragger::setColor(), osgManipulator::Scale2DDragger::setColor(), osgManipulator::Scale1DDragger::setColor(), osgManipulator::RotateSphereDragger::setColor(), and osgManipulator::RotateCylinderDragger::setColor().
Generated at Mon Aug 1 2011 15:38:48 for the OpenSceneGraph by doxygen 1.7.1.