OpenSceneGraph: osgText Namespace Reference
osgText Namespace Reference
The osgText library is a NodeKit that extends the core scene graph to support high quality text.
Classes
class FadeText
class Font
Pure virtual base class for fonts.
class Glyph
class GlyphGeometry
class Glyph3D
class GlyphTexture
class VectorUInt
class String
class Bevel
class Style
class Text
class Text3D
class TextBase
Typedefs
typedef Font Font3D
typedef std::pair< unsigned
int, unsigned int > FontResolution
Enumerations
enum KerningType { KERNING_DEFAULT, KERNING_UNFITTED, KERNING_NONE }
Functions
OSGTEXT_EXPORT Font * readFontFile (const std::string &filename, const osgDB::Options *userOptions=0)
Read a font from specified file.
OSGTEXT_EXPORT Font * readFontStream (std::istream &stream, const osgDB::Options *userOptions=0)
read a font from specified stream.
OSGTEXT_EXPORT osg::ref_ptr< Font > readRefFontFile (const std::string &filename, const osgDB::Options *userOptions=0)
OSGTEXT_EXPORT osg::ref_ptr< Font > readRefFontStream (std::istream &stream, const osgDB::Options *userOptions=0)
OSGTEXT_EXPORT std::string findFontFile (const std::string &str)
Font * readFont3DFile (const std::string &filename, const osgDB::ReaderWriter::Options *userOptions=0)
deprecated, use readFontFile() instead.
Font * readFont3DStream (std::istream &stream, const osgDB::ReaderWriter::Options *userOptions=0)
deprecated, use readFontStream() instead.
osg::ref_ptr< Font > readRefFont3DFile (const std::string &filename, const osgDB::ReaderWriter::Options *userOptions=0)
deprecated, use readRefFontFile() instead.
osg::ref_ptr< Font > readRefFont3DStream (std::istream &stream, const osgDB::ReaderWriter::Options *userOptions=0)
deprecated, use readRefFontStream() instead.
std::string findFont3DFile (const std::string &str)
deprecated, use findFontFile() instead.
Detailed Description
The osgText library is a NodeKit that extends the core scene graph to support high quality text.
Typedef Documentation
typedef Font osgText::Font3D
typedef std::pair< unsigned int, unsigned int > osgText::FontResolution
Enumeration Type Documentation
enum osgText::KerningType
Enumerator:
KERNING_DEFAULT
KERNING_UNFITTED
KERNING_NONE
Function Documentation
std::string osgText::findFont3DFile (const std::string & str) [inline]
deprecated, use findFontFile() instead.
References findFontFile().
OSGTEXT_EXPORT std::string osgText::findFontFile (const std::string & str)
Referenced by findFont3DFile().
Font* osgText::readFont3DFile (const std::string & filename, const osgDB::ReaderWriter::Options * userOptions = 0) [inline]
deprecated, use readFontFile() instead.
References readFontFile().
Font* osgText::readFont3DStream (std::istream & stream, const osgDB::ReaderWriter::Options * userOptions = 0) [inline]
deprecated, use readFontStream() instead.
References readFontStream().
OSGTEXT_EXPORT Font* osgText::readFontFile (const std::string & filename, const osgDB::Options * userOptions = 0)
Read a font from specified file.
The filename may contain a path. It will search for the font file in the following places in this order:
In the current directory
All paths defined in OSG_FILE_PATH or OSGFILEPATH environment variable
Filename with path stripped: In the current directory
Filename with path stripped: All paths defined in OSG_FILE_PATH or OSGFILEPATH
Then the file will be searched in OS specific directories in the following order:
Again in the current directory
Windows: In C:/winnt/fonts
Windows: In C:/windows/fonts
Windows: In the fonts directory of the windows install directory
Other OS: In /usr/share/fonts/ttf
Other OS: In /usr/share/fonts/ttf/western
Other OS: In /usr/share/fonts/ttf/decoratives
If the given file could not be found, the path part will be stripped and the file will be searched again in the OS specific directories.
Referenced by readFont3DFile().
OSGTEXT_EXPORT Font* osgText::readFontStream (std::istream & stream, const osgDB::Options * userOptions = 0)
read a font from specified stream.
Referenced by readFont3DStream().
osg::ref_ptr<Font> osgText::readRefFont3DFile (const std::string & filename, const osgDB::ReaderWriter::Options * userOptions = 0) [inline]
deprecated, use readRefFontFile() instead.
References readRefFontFile().
osg::ref_ptr<Font> osgText::readRefFont3DStream (std::istream & stream, const osgDB::ReaderWriter::Options * userOptions = 0) [inline]
deprecated, use readRefFontStream() instead.
References readRefFontStream().
OSGTEXT_EXPORT osg::ref_ptr<Font> osgText::readRefFontFile (const std::string & filename, const osgDB::Options * userOptions = 0)
Referenced by readRefFont3DFile().
OSGTEXT_EXPORT osg::ref_ptr<Font> osgText::readRefFontStream (std::istream & stream, const osgDB::Options * userOptions = 0)
Referenced by readRefFont3DStream().
Generated at Mon Aug 1 2011 15:38:49 for the OpenSceneGraph by doxygen 1.7.1.